Repository guacsec/guac, pull requests merged in 2022-12, with the labels that each got.

#245 add vulnerability certifier
  go.mod
  go.sum
  pkg/assembler/graphdb/graphdb_test_utils.go
  pkg/certifier/certifier.go
  pkg/certifier/certify/certify.go
  pkg/certifier/components/root_package.go
  pkg/certifier/osv/internal/osv_query/osv_query.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/XXL

#257 docs: add a listing of supported input formats
  README.md
Labels: size/XS

#246 Add Certifier cmd to guacone
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
  go.mod
  go.sum
Labels: size/L

#263 fix: reorg internal folder to consolidate
  internal/testing/dochelper/dochelper.go
  internal/testing/keyutil/keyutil.go
  internal/testing/mockverifier/mockverifier.go
  internal/testing/processor/testdata.go
  internal/testing/simpledoc/simpledoc.go
  internal/testing/testdata/exampledata/alpine-cyclonedx.json
  internal/testing/testdata/exampledata/alpine-small-spdx.json
  internal/testing/testdata/exampledata/alpine-spdx.json
  internal/testing/testdata/exampledata/big-mongo-cyclonedx.json
  internal/testing/testdata/exampledata/busybox-cyclonedx.json
  internal/testing/testdata/exampledata/certify-vuln.json
  internal/testing/testdata/exampledata/crev-review.json
  internal/testing/testdata/exampledata/distroless-cyclonedx.json
  internal/testing/testdata/exampledata/github-review.json
  internal/testing/testdata/exampledata/invalid-cyclonedx.json
  internal/testing/testdata/exampledata/invalid-scorecard.json
  internal/testing/testdata/exampledata/invalid-spdx.json
  internal/testing/testdata/exampledata/kubernetes-scorecard.json
  internal/testing/testdata/exampledata/quarkus-deps-cyclonedx.json
  internal/testing/testdata/exampledata/small-deps-cyclonedx.json
  internal/testing/testdata/exampledata/small-spdx.json
  internal/testing/testdata/testdata.go
  pkg/handler/processor/cyclonedx/cyclonedx_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/test_cyclonedx_test.go
  pkg/handler/processor/guesser/type_ite6_test.go
  pkg/handler/processor/guesser/type_scorecard_test.go
  pkg/handler/processor/guesser/type_spdx_test.go
  pkg/handler/processor/ite6/ite6_test.go
  pkg/handler/processor/process/process_test.go
  pkg/handler/processor/scorecard/scorecard_test.go
  pkg/handler/processor/spdx/spdx_test.go
  pkg/ingestor/key/inmemory/inmemory_test.go
  pkg/ingestor/key/key_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/dsse/parser_dsse_test.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
  pkg/ingestor/parser/slsa/parser_slsa_test.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
  pkg/ingestor/parser/vuln/certify_vuln_test.go
  pkg/ingestor/verifier/verifier_test.go
Labels: size/XL

#271 Add Luke to TAM
  TECHNICAL_ADVISORY_MEMBERS
Labels: size/XS

#272 Consolidate duplicate flag declarations
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
Labels: size/S

#276 Viper config implementation
  SETUP.md
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
  cmd/ingest/cmd/example.go
  cmd/ingest/cmd/root.go
  go.mod
  go.sum
  guac.yaml
  internal/testing/simpledoc/simpledoc.go
Labels: size/L

#270 fix: handled error state when cyclonedx dependencies are missing a depends on property
  internal/testing/testdata/exampledata/npm-cyclonedx-dependencies-missing-depends-on.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/M

#284 fix: viper flag name missmatch
  cmd/guacone/cmd/root.go
  cmd/ingest/cmd/root.go
Labels: size/XS

#228 Create a Git document collector
  go.mod
  go.sum
  pkg/handler/collector/git/git.go
  pkg/handler/collector/git/git_test.go
Labels: size/L
