Repository guacsec/guac, pull requests merged in 2022-11, with the labels that each got.

#201 removed affiliation for bmitch
  TECHNICAL_ADVISORY_MEMBERS
Labels: size/XS

#207 fix bug#199
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: size/S

#231 Fix package overwite cipher bug
  pkg/assembler/helper.go
  pkg/assembler/nodes.go
Labels: size/M

#229 remove all logrus calls. Add ctx
  go.mod
  internal/testing/ingestor/testdata/testdata.go
  pkg/handler/collector/gcs/gcs.go
  pkg/ingestor/key/inmemory/inmemory.go
  pkg/ingestor/key/inmemory/inmemory_test.go
  pkg/ingestor/key/key.go
  pkg/ingestor/key/key_test.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier_test.go
  pkg/ingestor/verifier/verifier.go
  pkg/ingestor/verifier/verifier_test.go
Labels: size/L

#224 Bug#206: Parse and include dependencies of CDX format
  internal/testing/ingestor/testdata/testdata.go
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/quarkus-deps-cyclonedx.json
  internal/testing/processor/testdata/small-deps-cyclonedx.json
  pkg/handler/processor/cyclonedx/cyclonedx_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/XXL

#237 return non 0 errcode if ingestion has errors
  cmd/guacone/cmd/files.go
Labels: size/S

#238 Fix: Bug #236
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: size/M

#233 update guesser and processor for ITE6 OSV Certifier attestation
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/certify-osv.json
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_ite6.go
  pkg/handler/processor/guesser/type_ite6_test.go
  pkg/handler/processor/ite6/ite6.go
  pkg/handler/processor/ite6/ite6_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
Labels: size/M

#241 add vulnerability certifier parser
  internal/testing/ingestor/testdata/testdata.go
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/certify-osv.json
  internal/testing/processor/testdata/certify-vuln.json
  pkg/certifier/attestation/attestation_vuln.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_ite6_test.go
  pkg/handler/processor/ite6/ite6_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
  pkg/ingestor/parser/vuln/certify_vuln_test.go
Labels: size/XL

#248 update guac logo
  README.md
Labels: size/XS
