Repository guacsec/guac, pull requests merged in 2022-09, with the labels that each got.

#86 Ingest/assembler example command
  cmd/ingest/cmd/data.go
  cmd/ingest/cmd/example.go
  cmd/ingest/cmd/root.go
  cmd/ingest/main.go
  pkg/assembler/assembler.go
  pkg/assembler/nodes.go
Labels: size/L

#92 Fix lint err
  cmd/ingest/cmd/example.go
Labels: size/XS

#93 Tag `nodes_test` as integration (requires graphdb)
  pkg/assembler/nodes_test.go
Labels: size/XS

#94 split ci tests into unit and integration
  .github/workflows/ci.yaml
Labels: size/S

#79 Add file collector
  pkg/handler/collector/file/file.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/file/testdata/hello
Labels: size/L

#99 guac all-in-one cmdline
  Makefile
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
  cmd/guacone/main.go
  pkg/handler/processor/ite6/ite6.go
  pkg/handler/processor/process/process.go
Labels: size/L

#61 fix: update collect interface
  cmd/collector/cmd/example.go
  cmd/guacone/cmd/files.go
  pkg/handler/collector/collector.go
Labels: size/L

#103 refactor ingestor in preparation for pluggability
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/L

#104 add spdx document processor
  go.mod
  go.sum
  pkg/handler/processor/processor.go
  pkg/handler/processor/spdx/spdx.go
  pkg/handler/processor/spdx/spdx_test.go
  pkg/handler/processor/spdx/testdata/alpine-spdx.json
  pkg/handler/processor/spdx/testdata/invalid-spdx.json
  pkg/handler/processor/spdx/testdata/small-spdx.json
Labels: size/XXL

#109 add spdx guesser
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/alpine-spdx.json
  internal/testing/processor/testdata/invalid-spdx.json
  internal/testing/processor/testdata/small-spdx.json
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/guesser/type_spdx.go
  pkg/handler/processor/guesser/type_spdx_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/spdx/spdx_test.go
Labels: size/L

#107 add package node and edges
  internal/testing/ingestor/testdata/testdata.go
  pkg/assembler/helper.go
  pkg/assembler/nodes.go
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/L
