Repository guacsec/guac, pull requests merged in 2022-10, with the labels that each got.

#118 add contributing to issues
  CONTRIBUTING.md
Labels: size/XS

#131 address comments from PR 108
  internal/testing/ingestor/testdata/testdata.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/dsse/parser_dsse_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/slsa/parser_slsa_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L, needs-review

#139 Fix preallocated map size
  pkg/assembler/graphdb.go
Labels: size/XS, needs-review

#105 minor collect changes
  cmd/collector/cmd/example.go
  pkg/handler/collector/collector.go
Labels: size/S, needs-review

#117 Add technical advisory members
  TECHNICAL_ADVISORY_MEMBERS
Labels: priority, size/S, needs-review

#132 add remy maintainer
  MAINTAINERS
Labels: size/XS, needs-review

#127 Add scorecard guesser/processor
  go.mod
  go.sum
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/invalid-scorecard.json
  internal/testing/processor/testdata/kubernetes-scorecard.json
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/guesser/type_scorecard.go
  pkg/handler/processor/guesser/type_scorecard_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/handler/processor/scorecard/scorecard.go
  pkg/handler/processor/scorecard/scorecard_test.go
Labels: priority, size/L, needs-review

#145 rebase parser so no extra unit tests needed
  pkg/ingestor/parser/parser.go
Labels: size/M

#144 fix issue 138 for stray quotes
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/XS, needs-review

#64 feat: implement json lines processor
  pkg/handler/processor/guesser/format_guesser.go
  pkg/handler/processor/guesser/format_jsonlines.go
  pkg/handler/processor/guesser/format_jsonlines_test.go
  pkg/handler/processor/jsonlines/jsonlines.go
  pkg/handler/processor/jsonlines/jsonlines_test.go
  pkg/handler/processor/processor.go
Labels: size/L

#140 Cyclonedx support
  go.mod
  go.sum
  internal/testing/ingestor/testdata/testdata.go
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/alpine-cyclonedx.json
  internal/testing/processor/testdata/big-mongo-cyclonedx.json
  internal/testing/processor/testdata/busybox-cyclonedx.json
  internal/testing/processor/testdata/distroless-cyclonedx.json
  internal/testing/processor/testdata/invalid-cyclonedx.json
  pkg/handler/processor/cyclonedx/cyclonedx.go
  pkg/handler/processor/cyclonedx/cyclonedx_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/test_cyclonedx_test.go
  pkg/handler/processor/guesser/type_cyclonedx.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/parser.go
Labels: size/XXL, needs-review

#146 minor spdx bug fixes for heuristics
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/S

#148 fix CI unit test issues from PR 146
  internal/testing/ingestor/testdata/testdata.go
Labels: size/S

#149 ingestor plugin registered as func instead of static struct
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/dsse/parser_dsse_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#114 feat: implement xml guesser
  pkg/handler/processor/guesser/format_guesser.go
  pkg/handler/processor/guesser/format_xml.go
  pkg/handler/processor/guesser/format_xml_test.go
  pkg/handler/processor/processor.go
Labels: size/M

#152 add additional tag info
  internal/testing/ingestor/testdata/testdata.go
  pkg/assembler/nodes.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/S

#126 Add developer documentation
  CONTRIBUTING.md
  GOVERNANCE.md
  Makefile
  README.md
  SETUP.md
Labels: size/L, needs-review

#130 Scorecards parser
  cmd/guacone/cmd/files.go
  pkg/assembler/nodes.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
Labels: size/L, needs-review

#162 Add POC to setup.md
  SETUP.md
Labels: size/L, needs-review

#143 add collector source information
  internal/testing/ingestor/testdata/testdata.go
  pkg/assembler/helper.go
  pkg/assembler/nodes.go
  pkg/assembler/nodes_test.go
  pkg/handler/collector/gcs/gcs.go
  pkg/handler/collector/gcs/gcs_test.go
  pkg/handler/processor/spdx/spdx_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#164 add Version field in PacakgeNode
  internal/testing/ingestor/testdata/testdata.go
  pkg/assembler/nodes.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M

#166 update readme
  README.md
Labels: size/M

#167 remove query debug msg
  pkg/assembler/graphdb.go
Labels: size/XS

#170 Update README.md with dev disclaimer
  README.md
Labels: size/XS

#172 fix CDX dependency edge and add tags
  internal/testing/ingestor/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: bug, size/S

#173 Update POC to account for cdx data difference with spdx
  SETUP.md
Labels: size/XS

#174 Add instructions to start docker with apoc
  SETUP.md
Labels: size/S

#175 Create indices in guacone
  cmd/guacone/cmd/files.go
  pkg/assembler/graphdb.go
Labels: size/M

#178 Change readme comm wording
  README.md
Labels: size/XS

#154 update assembler and processor for CREV and Certify attestation
  internal/testing/processor/testdata.go
  internal/testing/processor/testdata/crev-review.json
  internal/testing/processor/testdata/github-review.json
  pkg/assembler/nodes.go
  pkg/assembler/nodes_test.go
  pkg/handler/processor/dsse/dsse.go
  pkg/handler/processor/dsse/dsse_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_ite6.go
  pkg/handler/processor/guesser/type_ite6_test.go
  pkg/handler/processor/ite6/ite6.go
  pkg/handler/processor/ite6/ite6_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
Labels: size/L, needs-review

#181 Increase golanglint ci timeout
  .gitignore
  .golangci.yaml
Labels: size/XS

#183 Update .kodiak.toml
  .github/.kodiak.toml
Labels: size/XS

#186 Revert "Update .kodiak.toml"
  .github/.kodiak.toml
Labels: size/XS

#187 update kodiak to not autoupdate
  .github/.kodiak.toml
Labels: size/XS
