Repository guacsec/guac, pull requests merged in 2023-04, with the labels that each got.

#663 Remove root nodes from vulnerabilities
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/cve_ghsa_osv.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/osv.graphql
Labels: size/XL

#670 update gqlgen from 0.17.27 to 0.17.28
  go.mod
  go.sum
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/cve.resolvers.go
  pkg/assembler/graphql/resolvers/ghsa.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/resolvers/isVulnerability.resolvers.go
  pkg/assembler/graphql/resolvers/osv.resolvers.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
Labels: size/XS

#660 Add deps.dev cmd implementation of collector subscriber
  cmd/collector/cmd/deps_dev.go
  internal/testing/testdata/testdata.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/parser.go
Labels: size/L

#551 update guac purl uri
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/S

#662 Add SETUP-new.md and supporting query and script files.
  README.md
  SETUP.md
  demo/GraphQL.md
  demo/path.py
  demo/queries.gql
  pkg/assembler/backends/README.md
  pkg/assembler/clients/README.md
  pkg/assembler/graphql/README.md
  pkg/assembler/graphql/examples/artifact_builder.gql
Labels: size/XXL

#671 update gql to compile for codegen
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/is_vulnerability.gql
Labels: size/M

#676 Improve logging when ingesting files
  cmd/guacone/cmd/files.go
Labels: size/S

#674 added cli for certifyBad and good
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/files.go
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
Labels: size/L

#679 Add Node query
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/path.go
  pkg/assembler/backends/neo4j/path.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/M

#677 Grab read mutex on Path and Neighbors.
  pkg/assembler/backends/inmem/path.go
Labels: size/XS

#680 Fix mutex locking in ingest package and source.
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
Labels: size/L

#673 Add NoKnownVuln node and related operations.
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/ui_opts.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/path.graphql
Labels: size/L

#682 add isOccurrence for CDX and fix issue with passing by value
  internal/testing/testdata/exampledata/small-deps-cyclonedx.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/vuln/vuln.go
Labels: size/L

#683 Update vuln parser to handle NoVuln node and update unit tests
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/scorecard.go
  cmd/pubsub_test/cmd/certifier.go
  internal/testing/testdata/exampledata/certify-novuln.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/operations/path.graphql
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/components/root_package/root_package.go
  pkg/ingestor/parser/vuln/vuln.go
  pkg/ingestor/parser/vuln/vuln_test.go
Labels: size/L

#685 Add end to end test
  .github/workflows/postmerge.yaml
  demo/GraphQL.md
  demo/path.py
  demo/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectCertifyVulnQ1.json
  internal/testing/e2e/expectIsDependencyQ1.json
  internal/testing/e2e/expectIsDependencyQ2.json
  internal/testing/e2e/expectOSVQ1.json
  internal/testing/e2e/expectPathPy.json
  internal/testing/e2e/expectPathQ1.json
  internal/testing/e2e/expectPkgQ1.json
  internal/testing/e2e/expectPkgQ2.json
  internal/testing/e2e/expectPkgQ3.json
  internal/testing/e2e/expectPkgQ4.json
Labels: size/XXL

#687 Fix some issues discovered with lint.
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
Labels: size/M

#690 change certifier name to osv and add polling and interval to cli
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/scorecard.go
  cmd/pubsub_test/cmd/files.go
  cmd/pubsub_test/cmd/osv.go
  cmd/pubsub_test/cmd/root.go
  internal/testing/e2e/e2e
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/components/root_package/root_package.go
Labels: size/L

#689 Update linter config. Add type assertion check.
  .github/workflows/ci.yaml
  .golangci.yaml
Labels: size/S

#691 Fix unchecked type assertions and index into index maps.
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
Labels: size/XL

#692 Fix more lint issues
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/graphdb/graphdb_test_utils.go
  pkg/collectsub/datasource/csubsource/csubsource_test.go
  pkg/handler/collector/gcs/gcs.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M

#694 update docker compose and add UI helpers
  docker-compose.yml
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/L

#695 fix versionRange missing from isDependency
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/common/helpers.go
Labels: size/L

#697 Move E2E test to PR.
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
  internal/testing/e2e/expectIsDependencyQ2.json
Labels: size/S

#681 Allow filtering neighbors and paths on GUAC verbs
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/path.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/neo4j/path.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
Labels: size/XL

#686 Add markdown format check to ci
  .github/workflows/ci.yaml
Labels: size/XS

#706 Fix NeighborsQuery to include edges
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/XS

#700 Add more error checking for inmem backend.
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/pkgEqual.go
Labels: size/L

#710 quiet down collectsub identifier strings
  cmd/ingest/cmd/ingest.go
Labels: size/XS

#696 Add vulnerability CLI to query if package is vulnerable
  cmd/guacone/cmd/query_vulnerability.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/cve.graphql
  pkg/assembler/clients/operations/ghsa.graphql
  pkg/assembler/clients/operations/isVulnerability.graphql
  pkg/assembler/clients/operations/osv.graphql
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/trees.graphql
Labels: size/L

#711 accept purls via cli for deps_dev
  cmd/collector/cmd/deps_dev.go
  pkg/certifier/certify/certify.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/M

#712 output vulnerability ID in path and fix lint issue
  cmd/guacone/cmd/query_vulnerability.go
  pkg/assembler/backends/inmem/pkg.go
Labels: size/M

#713 Fix certify flag
  cmd/guacone/cmd/certify.go
Labels: size/XS

#707 Improve purl handling in cdx and spdx parsers
  demo/GraphQL.md
  demo/queries.gql
  internal/testing/e2e/expectIsDependencyQ2.json
  internal/testing/e2e/expectPathPy.json
  internal/testing/e2e/expectPkgQ1.json
  internal/testing/e2e/expectPkgQ2.json
  internal/testing/e2e/expectPkgQ4.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L

#714 add missing fields to vex
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
Labels: size/L

#717 add annotation field to hasSBOM
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
Labels: size/M

#726 add release workflow to build and publish container image to ghcr
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: size/M

#732 update deps.dev unit test with new scorecard information
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
Labels: size/L

#727 query purl to find all transitive vulnerabilities
  cmd/guacone/cmd/query_vulnerability.go
Labels: size/L

#718 fix nil value error in certifyVuln and deps.dev for parsing GO packages
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
Labels: size/XL

#721 Update path.py to use the node query for first node.
  demo/GraphQL.md
  demo/path.py
  demo/queries.gql
  internal/testing/e2e/expectPathPy.json
Labels: size/M

#730 graphql doc review
  demo/GraphQL.md
Labels: size/M

#741 move markdown lint to lint CI and check for changes
  .github/workflows/ci.yaml
Labels: size/XS

#720 Tutorial for running GUAC with Docker Compose.
  docs/Compose.md
  docs/GUAC-diagram.svg
Labels: size/L

#744 change spdx guesser to check for namespace instead
  pkg/handler/processor/guesser/type_spdx.go
Labels: size/XS

#733 Remove guacone graphql. Rename playground to guac.
  .github/workflows/release.yaml
  Makefile
  cmd/guacgql/cmd/ingest.go
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  cmd/guacgql/main.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/graphql_server.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/query_vulnerability.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/scorecard.go
  demo/GraphQL.md
  docker-compose.yml
  internal/testing/e2e/e2e
Labels: size/L

#753 update release.yml workflow to use correct login
  .github/workflows/release.yaml
Labels: size/XS

#752 Move test_pubsub and examples to internal.
  Makefile
  cmd/guaccollect/cmd/example.go
  cmd/guacingest/cmd/example.go
  internal/testing/cmd/collect/cmd/example.go
  internal/testing/cmd/collect/cmd/mockcollector/mock_collector.go
  internal/testing/cmd/collect/cmd/root.go
  internal/testing/cmd/collect/main.go
  internal/testing/cmd/ingest/cmd/data.go
  internal/testing/cmd/ingest/cmd/example.go
  internal/testing/cmd/ingest/cmd/root.go
  internal/testing/cmd/ingest/main.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/cmd/pubsub_test/cmd/root.go
  internal/testing/cmd/pubsub_test/main.go
Labels: size/L

#751 add bad packages demo guide
  demo/bad_packages.md
Labels: size/L, needs-review

#757 add ontology docs
  docs/ontology-definitions.md
  docs/ontology.md
Labels: size/L

#750 Add contributor ladder process.
  CONTRIBUTING.md
Labels: size/L, needs-review

#742 Add query vulnerability CLI demo documentation
  CONTRIBUTING.md
  cmd/guacone/cmd/query_vulnerability.go
  demo/query_vuln.md
Labels: size/L, needs-review

#746 fix issue with dependent package purl on deps.dev and remove duplicates for vulnerability and hasSourceAt
  internal/testing/testdata/testdata.go
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/source/source.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
Labels: size/L

#438 Change OCI Collector log messages from Error to Info for missing repo metadata
  pkg/handler/collector/oci/oci.go
Labels: size/XS, needs-review

#767 Deps.dev system check
  internal/testing/testdata/testdata.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/L, needs-review

#759 Document workflow deps.dev and certifier
  demo/query_vuln.md
  demo/workflow/queries.gql
  demo/workflow/workflow.md
Labels: size/XL, needs-review

#772 CLI daemon/service commands exit gracefully.
  cmd/guaccollect/cmd/files.go
  cmd/guaccsub/cmd/root.go
  cmd/guacgql/cmd/server.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  pkg/certifier/certify/certify.go
  pkg/cli/store.go
  pkg/collectsub/server/server.go
  pkg/emitter/nats_data.go
  pkg/emitter/nats_emitter.go
  pkg/handler/collector/collector.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/gcs/gcs.go
  pkg/handler/collector/git/git.go
  pkg/handler/collector/github/github.go
  pkg/handler/collector/oci/oci.go
Labels: size/XL

#778 Added direct/indirect/unknown enum for IsDependency and update deps.dev collector/parser
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/XXL

#780 update hasSBOM schema to include fields from ResourceDescriptor
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
Labels: size/L

#784 add hasSBOM to SPDX and CDX parser
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/emitter/nats_emitter.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L

#723 Inmem backend unit tests
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/certifyBad_test.go
  pkg/assembler/backends/inmem/certifyGood_test.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVEXStatement_test.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/cve_test.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/ghsa_test.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/isVulnerability_test.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/osv_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
Labels: size/XXL

#785 Add GraphQL documentation doc.
  docs/GraphQL.md
  docs/graphql/package.png
  docs/graphql/source.png
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/pkgEqual.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers.go
  pkg/assembler/graphql/schema/artifact.graphql
  pkg/assembler/graphql/schema/builder.graphql
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyGood.graphql
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/assembler/graphql/schema/hasSourceAt.graphql
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
  pkg/assembler/graphql/schema/isVulnerability.graphql
  pkg/assembler/graphql/schema/osv.graphql
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/graphql/schema/path.graphql
  pkg/assembler/graphql/schema/pkgEqual.graphql
  pkg/assembler/graphql/schema/source.graphql
Labels: size/XXL

#787 CertifyScorecard unit tests
  docs/GraphQL.md
  internal/testing/ptrfrom/ptrfrom.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyScorecard_test.go
Labels: size/XL

#788 Change HasSBOM to Package or Artifact.
  cmd/guacgql/cmd/ingest.go
  docs/GraphQL.md
  pkg/assembler/assembler.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/path.graphql
Labels: size/L

#724 In memeory unit tests
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/artifact_test.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/builder_test.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/pkg_test.go
Labels: size/XXL

#792 build: improve building in non-docker environments
  Makefile
  dockerfiles/Dockerfile.guac-cont
  dockerfiles/Dockerfile.healthcheck
Labels: size/S

#782 add helper function to convert version ranges to constraints
  pkg/misc/depversion/depversion.go
  pkg/misc/depversion/depversion_test.go
Labels: size/XL

#781 User agent
  Makefile
  cmd/guaccollect/cmd/root.go
  cmd/guaccsub/cmd/root.go
  cmd/guacgql/cmd/root.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/root.go
  internal/client/githubclient/githubclient.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/gcs/gcs.go
  pkg/handler/collector/oci/oci.go
  pkg/version/version.go
Labels: size/M, needs-review

#796 Add WhichVersionMatchesfunction implementation
  go.mod
  go.sum
  pkg/misc/depversion/depversion.go
  pkg/misc/depversion/depversion_test.go
Labels: size/L

#789 Add templates for issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report_data_quality.md
  .github/ISSUE_TEMPLATE/bug_report_ingestion.md
  .github/ISSUE_TEMPLATE/bug_report_trust.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/L, needs-review

#794 sign image and upload sbom
  .github/workflows/release.yaml
Labels: size/M

#797 fix lint error: comment out unused vrange (for now)
  pkg/misc/depversion/depversion.go
Labels: size/S

#798 Fix typo from copy-paste in issue template
  .github/ISSUE_TEMPLATE/question.md
Labels: size/XS
