Repository guacsec/guac, pull requests merged in 2023-05, with the labels that each got.

#801 update query vuln to utilize proper dependency version range, add table and cleanup doc
  cmd/guacone/cmd/query_known.go
  cmd/guacone/cmd/query_vulnerability.go
  demo/query_vuln.md
Labels: size/L

#800 Unknown known demo/ remove pkgName flag from query
  cmd/guacone/cmd/query_known.go
  demo/query_known.md
Labels: size/L

#807 Add Certify bad query and re-org the query CLI
  cmd/guacone/cmd/query.go
  cmd/guacone/cmd/queryBad.go
  cmd/guacone/cmd/queryKnown.go
  cmd/guacone/cmd/queryVulnerability.go
  go.mod
  go.sum
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyBad.graphql
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/trees.graphql
Labels: size/L

#810 remove duplicate IDs from path for URL
  cmd/guacone/cmd/bad.go
  cmd/guacone/cmd/known.go
  cmd/guacone/cmd/vulnerability.go
  demo/query_known.md
  demo/query_vuln.md
Labels: size/M

#811 Unit tests for HasSBOM, HasSLSA, and HasSourceAt.
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/backends/inmem/hasSLSA_test.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hasSourceAt_test.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
Labels: size/XXL

#812 Add Nodes query needed for UI.
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/path.go
  pkg/assembler/backends/neo4j/path.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/graphql/examples/ui_opts.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/prelude.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/L

#813 Sync Graph doc to status after #812
  docs/GraphQL.md
Labels: size/XS

#771 add doc for using helm chart
  docs/HelmChart.md
Labels: size/L, needs-review

#764 make ingestor not hang when getting a doc parse error
  pkg/handler/processor/process/process.go
  pkg/handler/processor/process/process_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
Labels: size/S, needs-review

#814 add new certifyBad demo based on updates to CLI and UI
  cmd/guacone/cmd/bad.go
  cmd/guacone/cmd/vulnerability.go
  demo/bad_packages.md
  demo/query_known.md
  demo/query_vuln.md
Labels: size/L, needs-review

#816 prose wrap HelmChart.md
  docs/HelmChart.md
Labels: size/M

#819 Remove stray `}`
  docs/GraphQL.md
Labels: size/XS

#818 Unit tests for HashEqual, IsDependency, PkgEqual.
  pkg/assembler/backends/inmem/hashEqual_test.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isDependency_test.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/inmem/pkgEqual_test.go
Labels: size/XXL

#820 Rename flags
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/files.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guaccollect/cmd/root.go
  cmd/guacgql/cmd/root.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/bad.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/known.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/scorecard.go
  cmd/guacone/cmd/vulnerability.go
  container_files/guac/guac.yaml
  demo/GraphQL.md
  demo/bad_packages.md
  demo/query_known.md
  demo/query_vuln.md
  docs/Compose.md
  docs/HelmChart.md
  guac.yaml
  internal/testing/e2e/e2e
  pkg/cli/store.go
Labels: size/L

#821 add missing unit tests for pkg and source
  pkg/assembler/backends/inmem/pkg_test.go
  pkg/assembler/backends/inmem/src_test.go
Labels: size/L

#795 Clean up docs and remove old SETUP.md
  CONTRIBUTING.md
  README.md
  SETUP.md
  demo/bad_packages/bad_packages.md
  demo/graphql/GraphQL.md
  demo/graphql/path.py
  demo/graphql/queries.gql
  demo/query_known/query_known.md
  demo/query_vuln/query_vuln.md
  internal/testing/e2e/e2e
Labels: size/L, needs-review

#829 add default purl for cdx and consistent naming for purl
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: size/S

#822 add simple high level road map for guac
  ROADMAP.md
Labels: size/S

#435 Included scorecard action
  .github/workflows/scorecard.yml
Labels: size/M

#833 Restrict perms on ci workflow.
  .github/workflows/ci.yaml
Labels: size/XS

#834 update container image name
  docs/HelmChart.md
Labels: size/XS

#836 update occurrence node type to output more information
  cmd/guacone/cmd/known.go
Labels: size/M

#850 Fix broken link
  CONTRIBUTING.md
Labels: size/XS

#866 update vulnerable versions of dependencies
  go.mod
  go.sum
Labels: size/S

#869 Nuke the old graphdb code
  internal/testing/cmd/pubsub_test/cmd/files.go
  pkg/assembler/backends/neo4j/ingest_testdata.go
  pkg/assembler/graphdb.go
  pkg/assembler/graphdb/graphdb.go
  pkg/assembler/graphdb/graphdb_test.go
  pkg/assembler/graphdb/graphdb_test_utils.go
  pkg/assembler/nodes_test.go
Labels: size/XL

#871 point to community page for communications
  README.md
Labels: size/S

#867 Move graphql docs to guac-docs
  docs/GraphQL.md
  docs/graphql/package.png
  docs/graphql/source.png
Labels: size/XL

#872 update links to point to docs on readme
  README.md
Labels: size/S

#873 Fix duplicate vulnerability entries due to different attestation times
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/certifier/certify/certify.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/S

#875 Use `time.Equal` instead of UTC conversion + `==`.
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/hasSourceAt.go
Labels: size/XS

#855 fix version handling for top level and dependency components
  pkg/assembler/helpers/purl.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L

#877 make startedOn and finishedOn optional fields for hasSLSA
  cmd/guacgql/cmd/ingest.go
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSLSA_test.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/M

#876 comment out verification of DSSE until trust and identity is completed
  pkg/ingestor/parser/dsse/parser_dsse.go
Labels: size/S

#878 fix wording and link on readme
  CONTRIBUTING.md
  README.md
  docs/Compose.md
Labels: size/M

#879 fix link in readme
  README.md
Labels: size/XS

#880 set docs to point at docs site
  README.md
  demo/README.md
  demo/bad_packages/bad_packages.md
  demo/graphql/GraphQL.md
  demo/query_known/query_known.md
  demo/query_vuln/query_vuln.md
  demo/workflow/workflow.md
  docs/Compose.md
  docs/GUAC-diagram.svg
  docs/HelmChart.md
  docs/README.md
  docs/ontology-definitions.md
  docs/ontology.md
Labels: size/XXL

#882 fix logger error message output
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/emitter/nats_emitter.go
  pkg/emitter/nats_emitter_test.go
  pkg/handler/collector/collector_test.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/github/github.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/vuln/vuln.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier.go
Labels: size/L

#885 add guac links to past presentations
  README.md
Labels: size/XS

#886 DoesRangeInclude function
  pkg/misc/depversion/depversion.go
  pkg/misc/depversion/depversion_test.go
Labels: size/M

#884 Make ingestion from guacone parallel
  cmd/guacone/cmd/files.go
  go.mod
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/parallel.go
Labels: size/L

#900 Fix parallel ingest when guacgql is in docker.
  cmd/guacone/cmd/files.go
Labels: size/S
