Repository guacsec/guac, pull requests merged in 2023-02, with the labels that each got.

#389 Make sure every PR syncs generated files and generate schema again
  Makefile
  pkg/assembler/graphql/generated/schema.generated.go
  pkg/assembler/graphql/resolvers/schema.resolvers.go
Labels: size/M

#388 add usecase where the name is just the image name in cdx/spdx sbom created via syft
  SETUP.md
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#391 Add package trie GraphQL schema (before qualifiers)
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/schema.generated.go
  pkg/assembler/graphql/gqlgen.yml
  pkg/assembler/graphql/main/server.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/graphql/schema/schema.graphql
Labels: size/L

#397 Handle matching for no qualifiers.
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/package.graphql
Labels: size/S

#398 Add source trie GraphQL schema
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_pkg.go
  pkg/assembler/backends/testing/ingest_src.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
  pkg/assembler/graphql/schema/source.graphql
Labels: size/L

#402 Add mocked client for testing
  cmd/guacone/cmd/collectsub_client.go
  pkg/collectsub/client/client.go
  pkg/collectsub/client/mock.go
Labels: size/M

#420 Create inmemDataSource and change oci convention
  pkg/collectsub/datasource/csubsource/csubsource_test.go
  pkg/collectsub/datasource/filesource/filesource.go
  pkg/collectsub/datasource/filesource/filesource_test.go
  pkg/collectsub/datasource/inmemsource/inmemsource.go
  pkg/collectsub/datasource/inmemsource/inmemsource_test.go
Labels: size/L

#421 update oci collectors to use datasources
  cmd/collector/cmd/files.go
  cmd/collector/cmd/oci.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  pkg/collectsub/datasource/inmemsource/inmemsource_test.go
  pkg/handler/collector/oci/oci.go
  pkg/handler/collector/oci/oci_test.go
Labels: size/L

#422 Add resolvers based on selected fields
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
Labels: size/L

#426 bug: add missing check if identity is verified
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier.go
Labels: size/S

#423 Included Wrapcheck linter
  .golangci.yaml
Labels: size/XS

#425 create docker compose service
  Makefile
  container_files/guac/guac.yaml
  container_files/nats/js.conf
  docker-compose.yml
  dockerfiles/Dockerfile.guac-cont
  dockerfiles/Dockerfile.healthcheck
  guac.yaml
Labels: size/M

#433 Improve NATS Emitter Logging and Timeouts
  pkg/emitter/nats_emitter.go
Labels: size/XS

#150 feat: add xml support to cyclonedx handlers
  internal/testing/testdata/exampledata/invalid-cyclonedx.xml
  internal/testing/testdata/exampledata/laravel-cyclonedx.xml
  internal/testing/testdata/testdata.go
  pkg/handler/processor/cyclonedx/cyclonedx.go
  pkg/handler/processor/cyclonedx/cyclonedx_test.go
  pkg/handler/processor/guesser/test_cyclonedx_test.go
  pkg/handler/processor/guesser/type_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: size/XXL

#430 Add collectsub service and OCI collector to all-in-one deployment
  Makefile
  cmd/collector/cmd/files.go
  cmd/collector/cmd/oci.go
  cmd/collector/cmd/root.go
  cmd/guacone/cmd/collectsub_client.go
  container_files/guac/guac.yaml
  docker-compose.yml
  dockerfiles/Dockerfile.guac-cont
  guac.yaml
  pkg/handler/collector/oci/oci.go
Labels: size/L

#444 add get-identifiers function to parser interface
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
Labels: size/M

#436 Improve CollectSub server operations
  pkg/collectsub/server/server.go
Labels: size/XS

#442 Add Hash equal schema for GraphQL
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hashEqual.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_hashEqual.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/schema/hashEqual.graphql
Labels: size/L

#445 Fixed error statments
  pkg/handler/collector/file/file.go
  pkg/handler/processor/dsse/dsse.go
  pkg/handler/processor/process/process.go
Labels: size/S

#447 Add IsOccurrence to GraphQL Schema
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_isOccurrence.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/L

#451 Add isDependency attestation with testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_isDependency.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
Labels: size/L

#453 Fix issue when intermediate dependencies also contain vulnerabilities
  internal/testing/testdata/testdata.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/L

#449 Add simple SLSA identifier strings and provide integration with ingestor
  cmd/guacone/cmd/files.go
  cmd/ingest/cmd/example.go
  cmd/ingest/cmd/ingest.go
  cmd/ingest/cmd/root.go
  cmd/pubsub_test/cmd/certifier.go
  cmd/pubsub_test/cmd/files.go
  docker-compose.yml
  dockerfiles/Dockerfile.healthcheck
  pkg/collectsub/collectsub/input/identifier_strings.go
  pkg/collectsub/collectsub/input/identifier_strings_test.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/L, needs-review

#454 Ingest packages (mutation) on both backends
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_hasSBOM.go
  pkg/assembler/backends/testing/ingest_isDependency.go
  pkg/assembler/backends/testing/ingest_isOccurrence.go
  pkg/assembler/backends/testing/ingest_pkg.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/schema/package.graphql
Labels: size/L

#455 Add CertifyPkg schema with testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/ingest_certifyPkg.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifypkg.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifypkg.resolvers.go
  pkg/assembler/graphql/schema/certifypkg.graphql
Labels: size/L

#465 [pkg ingestion] Handle qualifiers in neo4j backend
  pkg/assembler/backends/neo4j/pkg.go
Labels: size/M

#464 Fixed parsing when bom contains no dependent components
  internal/testing/testdata/exampledata/no-dependent-components-cyclonedx.json
  internal/testing/testdata/testdata.go
  pkg/handler/processor/cyclonedx/cyclonedx_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#463 added certifyScorecard with testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/prelude.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
Labels: size/L

#466 Added certifyVuln schema with testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyPkg.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/schema/certifyPkg.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/L

#467 Added IsVulnerability schema and backend testing
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isVulnerability.resolvers.go
  pkg/assembler/graphql/schema/isVulnerability.graphql
Labels: size/L

#471 Added HasSLSA schema along with testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/schema/hasSLSA.graphql
Labels: size/L

#468 Added Certify VEX statement schema and testing backend
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
Labels: size/L

#474 Addressed issue 458 (inline comments and boolean cleanup)
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/certifyPkg.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyPkg.graphql
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/assembler/graphql/schema/hasSourceAt.graphql
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
  pkg/assembler/graphql/schema/isVulnerability.graphql
Labels: size/XL

#473 Add graphql query examples
  .graphqlconfig.yaml
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/cve_ghsa_osv.gql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/has_source_at.gql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/examples/is_vulnerability.gql
  pkg/assembler/graphql/examples/mutation.gql
  pkg/assembler/graphql/examples/packages.gql
  pkg/assembler/graphql/examples/source.gql
Labels: size/XXL

#477 [neo4j] Move qualifiers to a list within version
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/ingest_testdata.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/graphql/examples/packages.gql
Labels: size/L

#479 Fix first query example to make it work
  pkg/assembler/graphql/examples/packages.gql
Labels: size/S

#480 Merge SourceSpec and SourceQualifierInput
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/graphql/examples/source.gql
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/graphql/schema/source.graphql
Labels: size/L

#476 IsDependency & CertifyPkg neo4j implementation
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/pkg.go
Labels: size/XL

#481 Add ingestion for sources, on both backends
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/graphql/examples/source.gql
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/graphql/schema/source.graphql
Labels: size/L

#484 Ensure artifacts are treated the same on both backends:
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/testing/artifact.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/artifact.graphql
Labels: size/M

#486 Added checks for isDependency and certifyPkg
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/graphql/examples/is_dependency.gql
Labels: size/L

#485 Add mutation to ingest artifacts
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/testing/artifact.go
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/schema/artifact.graphql
Labels: size/L

#490 Ensure CI checks that generated code is up to date.
  .github/workflows/ci.yaml
  Makefile
Labels: size/XS

#487 enforce lowercase for vulnerabilities on both backends
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/ghsa.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/osv.graphql
Labels: size/M

#489 [neo4j] Added hasSourceAt neo4j query
  pkg/assembler/backends/neo4j/hasSourceAt.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/graphql/examples/has_source_at.gql
Labels: size/L

#483 Remove unnecessary `nil` checks
  pkg/assembler/backends/neo4j/pkg.go
Labels: size/S

#478 Check if tools are installed.
  Makefile
Labels: size/M

#491 Add mutation to ingest builders
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/builder.go
  pkg/assembler/backends/testing/builder.go
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/schema/builder.graphql
Labels: size/L

#496 Ingestion for the vulnerabilities
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/ingest_testdata.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/ghsa.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/graphql/examples/cve_ghsa_osv.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/cve.resolvers.go
  pkg/assembler/graphql/resolvers/ghsa.resolvers.go
  pkg/assembler/graphql/resolvers/osv.resolvers.go
  pkg/assembler/graphql/schema/artifact.graphql
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/osv.graphql
Labels: size/L

#494 [Neo4j] Added HashEqual neo4j backend implementation
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hashEqual.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/graphql/examples/hash_equal.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/schema/hashEqual.graphql
Labels: size/L

#493 [neo4j] isOccurrence query
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/L

#497 [neo4j] certifyBad Neo4j implementation
  pkg/assembler/backends/neo4j/cerifyBad.go
  pkg/assembler/backends/testing/certifyBad.go
Labels: size/L

#500 [neo4j] added neo4j implementation of hasSBOM
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
Labels: size/L

#501 [neo4j] added neo4j implementation of certifyScorecard
  pkg/assembler/backends/neo4j/cerifyBad.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/hasSBOM.go
Labels: size/L
