Repository guacsec/guac, pull requests merged in 2023-08, with the labels that each got.

#1113 Workaround depversion handling.
  cmd/guacone/cmd/vulnerability.go
  pkg/misc/depversion/depversion.go
Labels: size/M

#1103 Parse SPDX: manage relations with top level package
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#1115 update API for bulk ingestion for CertifyBad/CertifyGood, add missing unit tests, update collections on arango
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyBad_test.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyGood_test.go
  pkg/assembler/backends/inmem/certifyScorecard_test.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/backends/inmem/hasSLSA_test.go
  pkg/assembler/backends/inmem/hashEqual_test.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/certifyGood.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/operations/certifyBad.graphql
  pkg/assembler/clients/operations/certifyGood.graphql
  pkg/assembler/clients/operations/contact.graphql
  pkg/assembler/clients/operations/metadata.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyGood.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers.go
  pkg/assembler/graphql/resolvers/contact.resolvers.go
  pkg/assembler/graphql/resolvers/metadata.resolvers.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyGood.graphql
  pkg/assembler/graphql/schema/contact.graphql
  pkg/assembler/graphql/schema/metadata.graphql
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XXL

#1119 specify the version of the nats helm chart
  Tiltfile
Labels: size/XS

#1121 fix ui opts and examples for visualizer code gen
  pkg/assembler/graphql/examples/certify_good.gql
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/S

#1122 Remove UI Opts, add queries used by viz under packages
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/package.graphql
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/L

#1123 add `certifyBad` query, `certifyGood` ingestion and query, update bulk assembler
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/cve.go
  pkg/assembler/backends/arangodb/ghsa.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/osv.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/clients/helpers/bulk.go
Labels: size/XXL

#1126 [feature] GUAC-Neptune database connection
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  go.mod
  go.sum
  guac.yaml
  pkg/cli/store.go
Labels: size/L

#1129 [PatchPlanning] Add CLI cmd for patch planning
  cmd/guacone/cmd/patch.go
  pkg/cli/store.go
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
  pkg/guacanalytics/toposort.go
Labels: size/L

#1127 Added non-nil dereferencing to SLSA parser
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/slsa/parser_slsa_test.go
Labels: size/M

#1142 [PatchPlanning] Rename dependencies to dependents in search
  cmd/guacone/cmd/patch.go
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/S

#1144 Add @jeffmendoza as Maintainer.
  .github/CODEOWNERS
  MAINTAINERS
Labels: size/S

#1131 Removed Empty String Parents for Root Nodes
  pkg/guacanalytics/patchPlanning.go
Labels: size/M

#1133 Refactored and Included Tests for TopoSortFromBfsNodeMap
  cmd/guacone/cmd/patch.go
  pkg/guacanalytics/toposort.go
  pkg/guacanalytics/toposort_test.go
Labels: size/L

#1130 :book: Included comments for the bfs on patchPlanning
  pkg/guacanalytics/patchPlanning.go
Labels: size/S

#1161 Feature/arango certify vuln implementation
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/certifyVuln_test.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/XXL

#1125 Implement new IsDependency graphql to point to versions
  cmd/guacgql/cmd/ingest.go
  cmd/guacone/cmd/vulnerability.go
  demo/graphql/path.py
  demo/graphql/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectIsDependencyQ2.json
  internal/testing/e2e/expectPathPy.json
  internal/testing/testdata/exampledata/ingest_predicates.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isDependency_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/XXL

#1164 Fix XML format validation
  pkg/handler/processor/process/process.go
  pkg/handler/processor/process/process_test.go
Labels: size/M

#1146 Fixed a Potential Stack Overflow Error in findProductRef
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/csaf/parser_csaf_test.go
Labels: size/L

#1165 Feature/add novuln bool to vulnerability filter
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/certifyVuln_test.go
  pkg/assembler/backends/inmem/vulnerability.go
  pkg/assembler/backends/inmem/vulnerability_test.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/vulnerability.gql
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/vulnerability.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers.go
  pkg/assembler/graphql/resolvers/vulnerability.resolvers.go
  pkg/assembler/graphql/schema/vulnerability.graphql
Labels: size/L

#1159 Fix check for docker buildx
  Makefile
Labels: size/XS

#1170 Feature/add vuln metadata schema
  .github/scripts/excluded_from_copyright
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/vulMetadata.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/vulMetadata.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/vulMetadata.resolvers.go
  pkg/assembler/graphql/schema/vulMetadata.graphql
Labels: size/L

#1176 Add check for docker compose
  Makefile
Labels: size/S

#1157 Fixed Part of SemVer Issue
  pkg/misc/depversion/depversion.go
  pkg/misc/depversion/depversion_test.go
Labels: size/M

#1145 Minor fixes to error messages patch.go
  cmd/guacone/cmd/patch.go
Labels: size/S

#1180 Feature/add vuln metadata backend [inmem]
  .github/scripts/excluded_from_copyright
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/assembler.go
  pkg/assembler/assembler_test.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/vulnMetadata.go
  pkg/assembler/backends/inmem/vulnMetadata_test.go
  pkg/assembler/backends/inmem/vulnerability.go
  pkg/assembler/backends/neo4j/vulnMetadata.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/helpers/parallel.go
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/clients/operations/vulnMetadata.graphql
  pkg/assembler/graphql/examples/vuln_metadata.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/vulnMetadata.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/vulMetadata.resolvers.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers.go
  pkg/assembler/graphql/resolvers/vulnMetadata.resolvers.go
  pkg/assembler/graphql/resolvers/vulnerability.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
  pkg/assembler/graphql/schema/vulnMetadata.graphql
Labels: size/XXL

#1192 Updated CollectedPypiWheelAxle
  internal/testing/testdata/testdata.go
Labels: size/L

#1185 CertifyBad: refactor validation checks
  .github/scripts/excluded_from_copyright
  internal/testing/mocks/backend.go
  internal/testing/testdata/models.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyBad_test.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers_test.go
Labels: size/L

#1194 Fixed a Potential Stack Overflow Error in findPurl 2
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/csaf/parser_csaf_test.go
Labels: size/M

#1200 Tag ent tests
  .github/workflows/ci.yaml
  pkg/assembler/backends/ent/backend/artifact_test.go
  pkg/assembler/backends/ent/backend/certify_test.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/helpers_test.go
  pkg/assembler/backends/ent/backend/neighbors_test.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/package_test.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/ent/backend/scorecard_test.go
  pkg/assembler/backends/ent/backend/search_test.go
  pkg/assembler/backends/ent/backend/slsa_test.go
  pkg/assembler/backends/ent/backend/software_test.go
  pkg/assembler/backends/ent/backend/source_test.go
  pkg/assembler/backends/ent/backend/vex_test.go
  pkg/assembler/backends/ent/backend/vulnerability_test.go
Labels: size/M

#1184 [Feature] add ingestion (including bulk) and query for VEX in Arango and inmem
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/certifyVEXStatement.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVEXStatement_test.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/schema/builder.graphql
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
Labels: size/XXL

#1203 IngestVEXStatement resolver: fix `err` management
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
Labels: size/XS

#1202 Add 'integration' tag to golangci-lint
  .golangci.yaml
Labels: size/XS

#1204 add regen via make generate and add missing bulk ingest vex
  internal/testing/mocks/backend.go
  internal/testing/mocks/mockgen.go
Labels: size/XS

#1205 update readme to include backends and update supported types
  README.md
Labels: size/S

#1181 [feature] Adds a parser for CycloneDX Vex data
  internal/testing/testdata/exampledata/cyclonedx-unaffected-vex.json
  internal/testing/testdata/exampledata/cyclonedx-vex-affected.json
  internal/testing/testdata/exampledata/cyclonedx-vex.xml
  internal/testing/testdata/testdata.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/vulnMetadata.graphql
  pkg/handler/processor/cdx_vex/cdx_vex.go
  pkg/handler/processor/cdx_vex/cdx_vex_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/test_cyclonedx_test.go
  pkg/handler/processor/guesser/type_cyclonedx.go
  pkg/handler/processor/guesser/type_cyclonedx_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/cdx_vex/parser_cdx_vex.go
  pkg/ingestor/parser/cdx_vex/parser_cdx_vex_test.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/parser.go
Labels: size/XXL

#1209 prevent checking for dependency version in test so changes in this do…
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/S
