Repository guacsec/guac, pull requests merged in 2023-10, with the labels that each got.

#1334 Ent - CertifyVex implementation
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement_test.go
  pkg/assembler/backends/ent/backend/vex.go
  pkg/assembler/backends/ent/backend/vex_test.go
  pkg/assembler/backends/ent/certifyvex.go
  pkg/assembler/backends/ent/certifyvex/certifyvex.go
  pkg/assembler/backends/ent/certifyvex/where.go
  pkg/assembler/backends/ent/certifyvex_create.go
  pkg/assembler/backends/ent/certifyvex_query.go
  pkg/assembler/backends/ent/certifyvex_update.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/certifyvex.go
Labels: size/XXL

#1345 Fixed Race Condition in ingestor/verifier Test
  pkg/ingestor/verifier/verifier_test.go
Labels: size/XS

#1333 update go version
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  pkg/collectsub/datasource/csubsource/csubsource.go
Labels: size/M

#1351 Fix lint errors and increase golangci-lint timeout
  .golangci.yaml
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier_test.go
Labels: size/XS

#1352 Bump github.com/nats-io/nats-server
  go.mod
  go.sum
  pkg/assembler/backends/arangodb/artifact_test.go
  pkg/assembler/backends/arangodb/builder_test.go
  pkg/assembler/backends/arangodb/hashEqual_test.go
  pkg/assembler/backends/arangodb/pkg_test.go
  pkg/assembler/backends/arangodb/src_test.go
  pkg/assembler/backends/arangodb/vulnerability_test.go
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/license_test.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/vulnerability_test.go
  pkg/assembler/backends/inmem/hashEqual_test.go
  pkg/assembler/backends/inmem/license_test.go
  pkg/assembler/backends/inmem/vulnerability_test.go
Labels: size/M

#1338 Include Timestamps for Verbs
  cmd/guacgql/cmd/ingest.go
  cmd/guacone/cmd/certify.go
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyBad_test.go
  pkg/assembler/backends/inmem/certifyGood.go
  pkg/assembler/backends/inmem/certifyGood_test.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/examples/certify_good.gql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyGood.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers_test.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyGood.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/guacanalytics/patchPlanning_test.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L

#1324 Add a developer readme to the cli commands.
  cmd/README.md
Labels: size/L

#1353 Add SECURITY-INSIGHTS
  SECURITY-INSIGHTS.yml
Labels: size/L

#1355 remove gql-test-data
  cmd/guacgql/cmd/ingest.go
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  container_files/guac/guac.yaml
  guac.yaml
  pkg/cli/store.go
Labels: size/XXL

#1247 [feature] Unionize parsing for cdx SBOM and VEX data
  internal/testing/testdata/exampledata/cyclonedx-vex-affected.json
  internal/testing/testdata/testdata.go
  pkg/handler/processor/cdx_vex/cdx_vex.go
  pkg/handler/processor/cdx_vex/cdx_vex_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_cyclonedx.go
  pkg/handler/processor/guesser/type_cyclonedx_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/cdx_vex/parser_cdx_vex.go
  pkg/ingestor/parser/cdx_vex/parser_cdx_vex_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/parser.go
Labels: size/XL

#1356 Update packages for slices import
  cmd/guacgql/cmd/server.go
  pkg/assembler/backends/arangodb/artifact_test.go
  pkg/assembler/backends/arangodb/builder_test.go
  pkg/assembler/backends/arangodb/hashEqual_test.go
  pkg/assembler/backends/arangodb/pkg_test.go
  pkg/assembler/backends/arangodb/src_test.go
  pkg/assembler/backends/arangodb/vulnerability_test.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/license_test.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
  pkg/assembler/backends/ent/backend/vulnerability_test.go
  pkg/assembler/backends/inmem/certifyBad_test.go
  pkg/assembler/backends/inmem/certifyGood_test.go
  pkg/assembler/backends/inmem/certifyLegal.go
  pkg/assembler/backends/inmem/certifyLegal_test.go
  pkg/assembler/backends/inmem/certifyScorecard_test.go
  pkg/assembler/backends/inmem/certifyVEXStatement_test.go
  pkg/assembler/backends/inmem/certifyVuln_test.go
  pkg/assembler/backends/inmem/hasMetadata_test.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSLSA_test.go
  pkg/assembler/backends/inmem/hasSourceAt_test.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/hashEqual_test.go
  pkg/assembler/backends/inmem/isDependency_test.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/license_test.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/inmem/pkgEqual_test.go
  pkg/assembler/backends/inmem/pointOfContact_test.go
  pkg/assembler/backends/inmem/vulnEqual.go
  pkg/assembler/backends/inmem/vulnEqual_test.go
  pkg/assembler/backends/inmem/vulnMetadata_test.go
  pkg/assembler/backends/inmem/vulnerability_test.go
  pkg/ingestor/parser/common/license.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/XL

#1332 Change version list to map
  pkg/assembler/backends/inmem/helpers_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkgEqual_test.go
  pkg/assembler/backends/inmem/pkg_test.go
Labels: size/XL

#1347 SPDX Parser: ingest CPE from externalRefs
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#1380 Support TLS for graphql server
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  pkg/cli/store.go
Labels: size/S

#1379 fix: typo
  cmd/guacone/cmd/certifier.go
Labels: size/XS

#1383 Wait for guac server to start before running tests
  internal/testing/e2e/e2e
Labels: size/S

#1365 Ent - HasMetadata
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hasMetadata_test.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/ent.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/gql_node.go
  pkg/assembler/backends/ent/gql_pagination.go
  pkg/assembler/backends/ent/hasmetadata.go
  pkg/assembler/backends/ent/hasmetadata/hasmetadata.go
  pkg/assembler/backends/ent/hasmetadata/where.go
  pkg/assembler/backends/ent/hasmetadata_create.go
  pkg/assembler/backends/ent/hasmetadata_delete.go
  pkg/assembler/backends/ent/hasmetadata_query.go
  pkg/assembler/backends/ent/hasmetadata_update.go
  pkg/assembler/backends/ent/hook/hook.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/predicate/predicate.go
  pkg/assembler/backends/ent/schema/hasmetadata.go
  pkg/assembler/backends/ent/tx.go
Labels: size/XXL

#1384 refactor(depversion): avoid unnecessary byte/string conversion
  pkg/misc/depversion/depversion.go
Labels: size/S

#1397 edit arangosearch view to exclude subpath search results
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/search.go
Labels: size/XS

#1394 fix noVuln type not showing up when querying for known
  cmd/guacone/cmd/known.go
Labels: size/XS

#1385 Update query used in docs with new vuln structure.
  demo/workflow/queries.gql
Labels: size/S

#1390 Support TLS for csub server and clients
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guaccsub/cmd/root.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/collectsub_client.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/gcs_test.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/scorecard.go
  pkg/cli/store.go
  pkg/collectsub/client/client.go
  pkg/collectsub/server/server.go
Labels: size/L

#1392 Ent - HasMetadata: fix ingesting same twice
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hasMetadata_test.go
Labels: size/M

#1391 Ent - PointOfContact
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/pointOfContact_test.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/ent.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/gql_node.go
  pkg/assembler/backends/ent/gql_pagination.go
  pkg/assembler/backends/ent/hook/hook.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/pointofcontact.go
  pkg/assembler/backends/ent/pointofcontact/pointofcontact.go
  pkg/assembler/backends/ent/pointofcontact/where.go
  pkg/assembler/backends/ent/pointofcontact_create.go
  pkg/assembler/backends/ent/pointofcontact_delete.go
  pkg/assembler/backends/ent/pointofcontact_query.go
  pkg/assembler/backends/ent/pointofcontact_update.go
  pkg/assembler/backends/ent/predicate/predicate.go
  pkg/assembler/backends/ent/schema/pointofcontact.go
  pkg/assembler/backends/ent/tx.go
Labels: size/XXL

#1382 add flag to toggle getting deps.dev dependencies
  cmd/README.md
  cmd/guaccollect/cmd/deps_dev.go
  internal/testing/testdata/testdata.go
  pkg/cli/store.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/L

#1396 Certifier OSV: fixed emit func when polling
  cmd/guacone/cmd/osv.go
Labels: size/M

#1399 Updating Arango and Ent with KnownSince
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyBad_test.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyGood_test.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certify_test.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/billofmaterials.go
  pkg/assembler/backends/ent/billofmaterials/billofmaterials.go
  pkg/assembler/backends/ent/billofmaterials/where.go
  pkg/assembler/backends/ent/billofmaterials_create.go
  pkg/assembler/backends/ent/billofmaterials_update.go
  pkg/assembler/backends/ent/certification.go
  pkg/assembler/backends/ent/certification/certification.go
  pkg/assembler/backends/ent/certification/where.go
  pkg/assembler/backends/ent/certification_create.go
  pkg/assembler/backends/ent/certification_update.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/billofmaterials.go
  pkg/assembler/backends/ent/schema/certification.go
Labels: size/L

#1395 Enable Guacone to ingest json.bz2 files
  cmd/guacone/cmd/gcs_test.go
  internal/testing/testdata/exampledata/busybox-cyclonedx.json.bz2
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
Labels: size/M

#1278 Add support for OCI referrers
  internal/testing/testdata/exampledata/oci-kubectl-linux-amd64-in-toto.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-amd64-spdx-1.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-amd64-spdx.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-arm-v7-in-toto.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-arm-v7-spdx.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-arm64-in-toto.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-arm64-spdx-1.json
  internal/testing/testdata/exampledata/oci-kubectl-linux-arm64-spdx.json
  internal/testing/testdata/exampledata/oci-kubectl-windows-amd64-in-toto.json
  internal/testing/testdata/testdata.go
  pkg/handler/collector/oci/oci.go
  pkg/handler/collector/oci/oci_test.go
Labels: size/XXL, needs-review

#1416 Ent - VulnerabilityMetadata endpoints
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/ent/backend/vulnMetadata.go
  pkg/assembler/backends/ent/backend/vulnMetadata_test.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/ent.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/gql_node.go
  pkg/assembler/backends/ent/gql_pagination.go
  pkg/assembler/backends/ent/hook/hook.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/predicate/predicate.go
  pkg/assembler/backends/ent/schema/vulnerabilityid.go
  pkg/assembler/backends/ent/schema/vulnerabilitymetadata.go
  pkg/assembler/backends/ent/tx.go
  pkg/assembler/backends/ent/vulnerabilityid.go
  pkg/assembler/backends/ent/vulnerabilityid/vulnerabilityid.go
  pkg/assembler/backends/ent/vulnerabilityid/where.go
  pkg/assembler/backends/ent/vulnerabilityid_create.go
  pkg/assembler/backends/ent/vulnerabilityid_query.go
  pkg/assembler/backends/ent/vulnerabilityid_update.go
  pkg/assembler/backends/ent/vulnerabilitymetadata.go
  pkg/assembler/backends/ent/vulnerabilitymetadata/vulnerabilitymetadata.go
  pkg/assembler/backends/ent/vulnerabilitymetadata/where.go
  pkg/assembler/backends/ent/vulnerabilitymetadata_create.go
  pkg/assembler/backends/ent/vulnerabilitymetadata_delete.go
  pkg/assembler/backends/ent/vulnerabilitymetadata_query.go
  pkg/assembler/backends/ent/vulnerabilitymetadata_update.go
Labels: size/XXL, needs-review

#1403 feature/Arango - add path query for arango backend with unit tests
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/path.go
  pkg/assembler/backends/arangodb/path_test.go
Labels: size/L, needs-review

#1419 Feature/arango neighbors nouns query
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/artifact_test.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/builder.go
  pkg/assembler/backends/arangodb/builder_test.go
  pkg/assembler/backends/arangodb/license.go
  pkg/assembler/backends/arangodb/path.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/pkg_test.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/arangodb/vulnerability.go
Labels: size/XXL

#1420 Feature/arango neighbors verbs with tests
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyLegal.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/certifyVEXStatement.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/arangodb/hasMetadata.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hasSourceAt.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/path.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/arangodb/pkgEqual.go
  pkg/assembler/backends/arangodb/pointOfContact.go
  pkg/assembler/backends/arangodb/vulnEqual.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
Labels: size/XXL

#1432 add missing index for arango collections
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/arangodb/hasSourceAt.go
Labels: size/L, needs-review

#1400 Fixed the incorrect tests for deps_dev
  internal/testing/testdata/testdata.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/XL, needs-review

#1430 [bug] docker-compose.yaml starts postgres but does not use it
  docker-compose.yml
Labels: size/S, needs-review

#1367 Issue 966: Extend HasSBOM to include references to included software …
  internal/testing/e2e/e2e
  internal/testing/mocks/backend.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/path_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/package.graphql
  pkg/assembler/clients/operations/source.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/README.md
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/helpers/package.go
  pkg/assembler/graphql/helpers/package_test.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers_test.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/graphql/schema/path.graphql
  pkg/assembler/graphql/schema/source.graphql
Labels: size/XXL, needs-review

#1308 S3 collector implementation
  cmd/guacone/cmd/s3.go
  go.mod
  go.sum
  pkg/cli/store.go
  pkg/handler/collector/s3/bucket/bucket.go
  pkg/handler/collector/s3/bucket/encoding.go
  pkg/handler/collector/s3/messaging/kafka.go
  pkg/handler/collector/s3/messaging/message.go
  pkg/handler/collector/s3/messaging/sqs.go
  pkg/handler/collector/s3/s3.go
  pkg/handler/collector/s3/s3_test.go
Labels: size/XXL, needs-review

#1422 Add log level configuration
  guac.yaml
  pkg/cli/init.go
  pkg/cli/init_test.go
  pkg/cli/store.go
  pkg/logging/logger.go
  pkg/logging/logger_test.go
Labels: size/L, needs-review

#1437 fix: use unique sbom identifier for the uri field
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/S

#1439 Ent - PackageVersion: added index for improving IsDependency ingestion
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/packageversion.go
Labels: size/XS

#1440 Ent: Package,IsDependency concurrent bulk ingestions
  pkg/assembler/backends/ent/backend/certifyVuln_test.go
  pkg/assembler/backends/ent/backend/concurrently.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/helpers_test.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/package_test.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
  pkg/assembler/backends/ent/testutils/suite.go
Labels: size/L

#1361 Included option to run integration tests locally
  Makefile
  integration.docker-compose.yaml
Labels: size/M

#1450 Define edges within software tries related nodes
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/arangodb/vulnerability.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkg_test.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/inmem/vulnerability.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/XL
