Repository guacsec/guac, pull requests merged in 2023-01, with the labels that each got.

#295 update copyright script to do more relaxed checking of year
  .github/scripts/copywrite.sh
Labels: size/XS

#277 Fix typo in osv.PRODUCER_ID
  internal/testing/testdata/testdata.go
  pkg/certifier/osv/osv.go
Labels: size/S

#311 fix: add key and verifier registration to guacone cli
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
  pkg/ingestor/key/inmemory/inmemory.go
  pkg/ingestor/key/inmemory/inmemory_test.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier_test.go
Labels: size/M, needs-review

#312 update make fmt to skip pb codegen files
  Makefile
Labels: size/XS

#315 Included tests for pkg/assembler/helper
  pkg/assembler/helper_test.go
Labels: size/L

#306 Implementation of simple collect sub service and CLI
  Makefile
  SETUP.md
  cmd/guacone/cmd/collectsub_client.go
  cmd/guacone/cmd/collectsub_server.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/root.go
  go.mod
  go.sum
  pkg/collectsub/client/client.go
  pkg/collectsub/collectsub/collectsub.pb.go
  pkg/collectsub/collectsub/collectsub.proto
  pkg/collectsub/collectsub/collectsub_grpc.pb.go
  pkg/collectsub/collectsub/input/input.go
  pkg/collectsub/server/db/db.go
  pkg/collectsub/server/db/db_test.go
  pkg/collectsub/server/db/simpledb/simpledb.go
  pkg/collectsub/server/db/types/db.go
  pkg/collectsub/server/server.go
Labels: size/XL

#313 Test Pubsub cmd (NATS PR: 4 of 4)
  Makefile
  cmd/pubsub_test/cmd/certifier.go
  cmd/pubsub_test/cmd/files.go
  cmd/pubsub_test/cmd/root.go
  cmd/pubsub_test/main.go
  pkg/certifier/certify/certify_test.go
  pkg/emitter/nats_data.go
  pkg/emitter/nats_emitter.go
  pkg/emitter/nats_emitter_test.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/process/process_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
Labels: size/XL

#324 Update ctx for each test case in Git collector
  .gitignore
  pkg/handler/collector/git/git_test.go
Labels: size/XS

#320 Included Tests for pkg/certifier/osv/osv
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/L

#328 Fixed the Lint Issues
  pkg/certifier/osv/internal/osv_query/osv_query.go
  pkg/handler/collector/file/file.go
  pkg/handler/collector/gcs/gcs.go
Labels: size/S

#330 Fixed the stackoverflow for cyclonedx parsing
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/M

#332 doc: update setup.md for osv certifier
  SETUP.md
Labels: size/M

#321 feat: add de-duplication via NATs jetstream
  pkg/certifier/certify/certify_test.go
  pkg/emitter/nats_emitter.go
  pkg/emitter/nats_emitter_test.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/parser/parser.go
Labels: size/L, needs-review

#333 doc: shorten links in setup.md
  SETUP.md
Labels: size/XS

#337 Ensure recursion termination in certifyHelper in osv
  pkg/certifier/attestation/attestation_vuln.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/M

#338 Fixed typo in certifier type
  pkg/certifier/certifier.go
  pkg/certifier/certify/certify.go
Labels: size/S

#335 Upgrade to go 1.19
  .github/workflows/ci.yaml
  cmd/guacone/cmd/collectsub_client.go
  go.mod
Labels: size/S

#340 Modified certifier to be generic to allow for other component types
  cmd/guacone/cmd/certifier.go
  cmd/pubsub_test/cmd/certifier.go
  internal/testing/testdata/testdata.go
  pkg/certifier/certifier.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/L

#348 Fixed bugs in file collector
  pkg/handler/collector/file/file.go
  pkg/handler/collector/file/file_test.go
Labels: size/S

#334 Clean up dsse parser
  pkg/ingestor/parser/dsse/parser_dsse.go
Labels: size/S

#357 Add skip files for golangci.yaml
  .golangci.yaml
Labels: size/XS

#361 added community meeting google group to readme
  README.md
Labels: size/XS

#364 add heuristic note
  README.md
Labels: size/XS

#326 Create a GraphQL interface for backend
  .github/CODEOWNERS
  .github/scripts/copywrite.sh
  .github/scripts/excluded_from_copywrite
  Makefile
  go.mod
  go.sum
  pkg/assembler/backends/README.md
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/graphql/README.md
  pkg/assembler/graphql/generated/prelude.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/schema.generated.go
  pkg/assembler/graphql/gqlgen.yml
  pkg/assembler/graphql/graphql.go
  pkg/assembler/graphql/main/server.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/resolver.go
  pkg/assembler/graphql/resolvers/schema.resolvers.go
  pkg/assembler/graphql/schema.graphql
  tools/tools.go
Labels: size/XL

#363 Update comments for certify
  pkg/certifier/certify/certify.go
Labels: size/XS

#370 fix bug where the register function errored without actually overwriting the value
  pkg/certifier/certify/certify.go
  pkg/handler/collector/collector.go
  pkg/handler/processor/guesser/format_guesser.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/key/key.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/verifier/verifier.go
Labels: size/XS

#372 Fixes typo in setup
  SETUP.md
Labels: size/XS

#369 Fix typo: copyright instead of copywrite
  .github/scripts/copyright.sh
  .github/scripts/excluded_from_copyright
  Makefile
Labels: size/XS

#356 Metrics - Prometheus
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/metrics/prometheus.go
  pkg/metrics/prometheus_test.go
Labels: size/L

#355 Replaced returning err with fmt.Errorf
  pkg/handler/collector/git/git.go
  pkg/handler/collector/git/git_test.go
Labels: size/M

#375 update SETUP.md to lock to v0.0.1 release
  SETUP.md
Labels: size/S

#378 Update shell.nix to go 1.19
  shell.nix
Labels: size/XS

#318 Create CollectSource interface and file example
  go.mod
  pkg/collectsub/datasource/datasource.go
  pkg/collectsub/datasource/filesource/filesource.go
  pkg/collectsub/datasource/filesource/filesource_test.go
Labels: size/L, needs-review

#382 Add q1 2023 summit notes
  README.md
Labels: size/XS

#383 remove internal OSV query and pull from upstream OSV_scanner project
  go.mod
  go.sum
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/osv/internal/osv_query/osv_query.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
Labels: size/L

#384 add monthly community meetings cal link
  README.md
Labels: size/XS
