Repository guacsec/guac, pull requests merged in 2023-03, with the labels that each got.

#502 Split CertifyScorecard, separating subject from object.
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/graphql/examples/mutation.gql
  pkg/assembler/graphql/examples/source.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
Labels: size/L

#506 update sigstore, go-securesystemslib and in-toto-golang
  go.mod
  go.sum
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
  pkg/ingestor/verifier/sigstore_verifier/sigstore_verifier_test.go
Labels: size/M

#507 Bulldoze existing integration from ingestor to assembler to make way for graphQL
  cmd/guacone/cmd/files.go
  cmd/ingest/cmd/example.go
  cmd/ingest/cmd/ingest.go
  cmd/pubsub_test/cmd/certifier.go
  cmd/pubsub_test/cmd/files.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/neo4j/ingest_testdata.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/dsse/parser_dsse_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/slsa/parser_slsa_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
  pkg/ingestor/parser/vuln/certify_vuln_test.go
Labels: size/XXL

#503 [neo4j] Added neo4j implementation of IsVulnerability
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/neo4j/osv.go
Labels: size/L

#504 [neo4j] Added CertifyVEXStatement implementation
  pkg/assembler/backends/neo4j/cerifyBad.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
Labels: size/L

#505 [neo4j] Added CertifyVuln query Implementation
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/graphql/examples/certify_vuln.gql
Labels: size/L

#513 Ingest scorecard certifications in neo4j and in-memory backends
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyPkg.resolvers.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/cve.resolvers.go
  pkg/assembler/graphql/resolvers/ghsa.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/resolvers/isVulnerability.resolvers.go
  pkg/assembler/graphql/resolvers/osv.resolvers.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
Labels: size/L

#515 Fix matching on tag and commit for sources in in-memory backend.
  pkg/assembler/backends/testing/src.go
Labels: size/M

#517 Reword READMEs and add forgotten examples
  pkg/assembler/backends/README.md
  pkg/assembler/graphql/README.md
  pkg/assembler/graphql/examples/certify_scorecard.gql
Labels: size/L

#518 [neo4j] added neo4j implementation of hasSLSA
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/hasSLSA.go
Labels: size/XL

#499 Use RFC 3339 time format in the API
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
Labels: size/M

#520 Remove re-used code from neo4j backend
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/builder.go
  pkg/assembler/backends/neo4j/cerifyBad.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/neo4j/hasSourceAt.go
  pkg/assembler/backends/neo4j/hashEqual.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
Labels: size/XXL

#521 Add scorecard parser integration
  pkg/assembler/assembler.go
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
Labels: size/L

#522 Generate code for client-side queries for GUAC.
  .github/scripts/excluded_from_copyright
  Makefile
  cmd/graphql_playground/cmd/ingest.go
  cmd/graphql_playground/cmd/server.go
  pkg/assembler/backends/README.md
  pkg/assembler/clients/README.md
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/genqlient.yaml
  pkg/assembler/clients/graphql.go
  pkg/assembler/clients/operations/certifyScorecard.graphql
  pkg/assembler/graphql/README.md
Labels: size/L

#523 add gql-server cmd to guacone
  cmd/guacone/cmd/graphql_server.go
  cmd/guacone/cmd/root.go
  pkg/assembler/backends/testing/backend.go
Labels: size/L

#527 update docker compose to run gql server
  container_files/guac/guac.yaml
  docker-compose.yml
Labels: size/S

#528 rename placeholder struct
  cmd/guacone/cmd/files.go
  cmd/ingest/cmd/ingest.go
  cmd/pubsub_test/cmd/certifier.go
  cmd/pubsub_test/cmd/files.go
  pkg/assembler/assembler.go
  pkg/ingestor/parser/common/types.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
Labels: size/M

#526 added ingest isDependency for neo4j
  Makefile
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/schema/isDependency.graphql
Labels: size/L

#529 [client] Generate pointers for optional GQL args
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/genqlient.yaml
Labels: size/S

#532 [in-memory][backend] Fix index out of range
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/pkg.go
Labels: size/M

#533 temp fix for missing default values in gql
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/src.go
Labels: size/XS

#530 Change assembler/ingestion plumbing to use client gql model
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/root.go
  container_files/guac/guac.yaml
  pkg/assembler/assembler.go
  pkg/assembler/clients/README.md
  pkg/assembler/clients/helpers/assembler.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
Labels: size/L

#535 Added Ingest isOccurrence
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/L

#534 cmd/ingestor plumbing to gql
  cmd/ingest/cmd/example.go
  cmd/ingest/cmd/ingest.go
  cmd/ingest/cmd/root.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/ingestor/parser/common/graph_builder.go
Labels: size/L

#459 Scorecard Certifier
  Makefile
  cmd/guacone/cmd/scorecard.go
  go.mod
  internal/testing/mock/scorecard.go
  pkg/certifier/certifier.go
  pkg/certifier/components/source_artifact/source_artifact.go
  pkg/certifier/scorecard/scorecard.go
  pkg/certifier/scorecard/scorecardRunner.go
  pkg/certifier/scorecard/scorecardRunner_test.go
  pkg/certifier/scorecard/scorecard_test.go
  pkg/certifier/scorecard/types.go
Labels: size/XL, needs-review

#537 Add ctx to fix CI issues for scorecard
  cmd/guacone/cmd/scorecard.go
Labels: size/XS

#538 Fix issue with Time in Neo4j backend.
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/S

#543 Implement SPDX parsing with new ontology
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/ingestor/parser/scorecard/parser_scorecard_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/XL

#546 change to table driven tests
  cmd/graphql_playground/cmd/ingest.go
Labels: size/L

#536 Added ingest Vulnerability for both backends and cmd test data
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/XL

#544 change top level heuristic PURL to guac purl
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/XS

#549 Ingestion fixes: reduce log spam, time how long they take
  cmd/graphql_playground/cmd/ingest.go
Labels: size/L

#545 Plumb IsOccurence/IsDependency to assembler
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M

#550 Prepare for SLSA ingestion
  pkg/assembler/backends/neo4j/cerifyBad.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
Labels: size/L

#547 added ingest certifyPkg for both backends
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/testing/certifyPkg.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyPkg.graphql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyPkg.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyPkg.resolvers.go
  pkg/assembler/graphql/schema/certifyPkg.graphql
Labels: size/L

#553 Add ingestion mutation for SLSA
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/schema/hasSLSA.graphql
Labels: size/XL

#552 [Fix] Remove unneeded query and remove re-used code between backends
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/convert.go
  pkg/assembler/backends/helper/inputCheker.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/certifyPkg.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/XL

#556 added ingest certifyBad for in-memory with tests
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/inputCheker.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyBad.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/schema/certifyBad.graphql
Labels: size/XL

#558 ignore vim swp files
  .gitignore
Labels: size/XS

#559 Ingest hash equal for in-memory backend
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hashEqual.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/schema/hashEqual.graphql
Labels: size/L

#561 Add warning to readme to warn users of broken functionality
  README.md
Labels: size/XS

#562 fix source being duplicated and add missing deepEqual checks
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/backends/testing/src.go
Labels: size/M

#555 Split materials and builder from SLSA input
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/inputCheker.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSLSA.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/schema/hasSLSA.graphql
Labels: size/L

#563 fix pkg version check
  pkg/assembler/backends/testing/pkg.go
Labels: size/S

#566 Fix/finish SLSA ingestion in the in-memory backend
  SETUP.md
  docker-compose.yml
  internal/testing/testdata/exampledata/crev-review.json
  internal/testing/testdata/exampledata/github-review.json
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/helper/conversion.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/hasSourceAt.graphql
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
  pkg/collectsub/collectsub/collectsub.proto
  pkg/emitter/nats_emitter_test.go
  pkg/handler/processor/dsse/dsse_test.go
  pkg/handler/processor/ite6/ite6_test.go
  pkg/ingestor/verifier/verifier_test.go
Labels: size/L

#567 Ingest hasSBOM for in-memory backend
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
Labels: size/L

#565 added ingest hasSourceAt for in-memory backend with test
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/hasSourceAt.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSourceAt.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/schema/hasSourceAt.graphql
Labels: size/L

#498 Add Github Collector
  .github/workflows/ci.yaml
  cmd/collector/cmd/github.go
  go.mod
  go.sum
  internal/client/githubclient/githubclient.go
  internal/client/githubclient/githubclient_test.go
  internal/client/repo_client.go
  internal/testing/testdata/testdata.go
  pkg/collectsub/datasource/datasource.go
  pkg/handler/collector/github/github.go
  pkg/handler/collector/github/github_test.go
Labels: size/XXL

#569 Ingest IsVulnerability for in-memory backend
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/isVulnerability.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/is_vulnerability.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/isVulnerability.resolvers.go
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/isVulnerability.graphql
Labels: size/XL

#570 Ingest VEX Statement for in-memory backend
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyBad.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
Labels: size/XL

#557 Add Vcs URI parsing
  pkg/assembler/helpers/vcs.go
  pkg/assembler/helpers/vcs_test.go
Labels: size/L

#579 Update generated GraphQL code
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyPkg.resolvers.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/cve.resolvers.go
  pkg/assembler/graphql/resolvers/ghsa.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/resolvers/isVulnerability.resolvers.go
  pkg/assembler/graphql/resolvers/osv.resolvers.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
Labels: size/XS

#585 Update shell.nix with additional dependencies
  shell.nix
Labels: size/XS

#578 Update Collector tests to use collector.Collect to reduce duplication.
  pkg/handler/collector/collector.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/gcs/gcs_test.go
  pkg/handler/collector/git/git_test.go
  pkg/handler/collector/github/github_test.go
  pkg/handler/collector/oci/oci_test.go
Labels: size/L

#588 Update Vuln parser to new ontology
  internal/testing/ptrfrom/ptrfrom.go
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/helpers/vuln.go
  pkg/assembler/helpers/vuln_test.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/vuln/cerify_vuln.go
  pkg/ingestor/parser/vuln/certify_vuln_test.go
  pkg/ingestor/parser/vuln/vuln.go
  pkg/ingestor/parser/vuln/vuln_test.go
Labels: size/XXL

#587 Fix test for generated files being up-to-date.
  Makefile
Labels: size/XS

#482 Refactored Redundencys in gcs
  pkg/handler/collector/gcs/gcs.go
Labels: size/M

#589 PURL and GitHubRelease additions to collectsub/datasources
  Makefile
  cmd/guacone/cmd/collectsub_client.go
  pkg/collectsub/collectsub/collectsub.pb.go
  pkg/collectsub/collectsub/collectsub.proto
  pkg/collectsub/collectsub/collectsub_grpc.pb.go
  pkg/collectsub/datasource/csubsource/csubsource.go
  pkg/collectsub/datasource/csubsource/csubsource_test.go
  pkg/collectsub/datasource/datasource.go
Labels: size/L, needs-review

#582 plumb dsse parser to graphql (without trust)
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/dsse/parser_dsse.go
  pkg/ingestor/parser/dsse/parser_dsse_test.go
Labels: size/M, needs-review

#598 fix duplication issue with src, package and hasSourceAt. Make hasSourceAt back link a list
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_source_at.gql
  pkg/assembler/graphql/examples/packages.gql
  pkg/assembler/graphql/examples/source.gql
Labels: size/XL

#599 [memory] Add IDs for vulnerability (cve, osv, ghsa)
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/ghsa.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/cve_ghsa_osv.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/osv.graphql
Labels: size/XL

#605 add new path schema in graphql
  .github/scripts/excluded_from_copyright
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyPkg.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/M

#607 remove nonvalid gql syntax
  pkg/assembler/graphql/examples/certify_scorecard.gql
Labels: size/M

#600 Update artifacts, hashEquals, and isOccurrance with internal structs and ids
  go.mod
  go.sum
  pkg/assembler/backends/testing/artifact.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/examples/hash_equal.gql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/artifact.graphql
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
Labels: size/XL

#608 Update gql to work with gql javascript codegen
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/has_source_at.gql
  pkg/assembler/graphql/examples/hash_equal.gql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/examples/is_vulnerability.gql
Labels: size/L

#604 change cve year to integer in schema
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/testing/certifyVEXStatement.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/examples/cve_ghsa_osv.gql
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/prelude.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/helpers/vuln.go
  pkg/assembler/helpers/vuln_test.go
Labels: size/M

#609 Add reachability testdata
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/has_source_at.gql
Labels: size/L

#619 update fragment consistency and add typed queries for UI
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/has_source_at.gql
  pkg/assembler/graphql/examples/is_vulnerability.gql
  pkg/assembler/graphql/examples/opts.gql
Labels: size/L

#622 update certifyVuln and IsVuln to add IDs and backedges
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/ghsa.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/is_vulnerability.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/isVulnerability.graphql
Labels: size/XXL

#623 Update builder and hasSLSA inmem backend. Change HasSLSA to artifact only.
  cmd/graphql_playground/cmd/ingest.go
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/testing/artifact.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/builder.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSLSA.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/schema/builder.graphql
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/ingestor/parser/slsa/parser_slsa.go
Labels: size/XXL

#624 Add neighbors and path GraphQL queries.
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/neo4j/path.go
  pkg/assembler/backends/testing/artifact.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/builder.go
  pkg/assembler/backends/testing/certifyScorecard.go
  pkg/assembler/backends/testing/certifyVuln.go
  pkg/assembler/backends/testing/cve.go
  pkg/assembler/backends/testing/ghsa.go
  pkg/assembler/backends/testing/hasSLSA.go
  pkg/assembler/backends/testing/hasSourceAt.go
  pkg/assembler/backends/testing/hashEqual.go
  pkg/assembler/backends/testing/isDependency.go
  pkg/assembler/backends/testing/isOccurrence.go
  pkg/assembler/backends/testing/isVulnerability.go
  pkg/assembler/backends/testing/osv.go
  pkg/assembler/backends/testing/path.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyPkg.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/isVulnerability.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/path.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/XL

#625 Update HasSBOM with ids and backedges.
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/hasSBOM.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/backends/testing/src.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
Labels: size/L

#628 Add ID and backedges for certifyPkg.
  cmd/guacone/cmd/graphql_server.go
  pkg/assembler/backends/testing/backend.go
  pkg/assembler/backends/testing/certifyPkg.go
  pkg/assembler/backends/testing/pkg.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyPkg.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyPkg.graphql
Labels: size/L

#630 Backend cleanup and rename
  cmd/graphql_playground/cmd/server.go
  cmd/guacone/cmd/graphql_server.go
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyPkg.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/path.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/builder.go
  pkg/assembler/backends/neo4j/certifyBad.go
  pkg/assembler/backends/neo4j/certifyPkg.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/backends/neo4j/certifyVEXStatement.go
  pkg/assembler/backends/neo4j/certifyVuln.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/hasSBOM.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/backends/neo4j/hasSourceAt.go
  pkg/assembler/backends/neo4j/hashEqual.go
  pkg/assembler/backends/neo4j/ingest_testdata.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/isVulnerability.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/neo4j/path.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
Labels: size/XL

#633 add evidence query and missing fragments
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/M

#634 Update OSV and Scorecard certifier to new ontology and add unit tests
  cmd/guacone/cmd/certifier.go
  cmd/pubsub_test/cmd/certifier.go
  internal/testing/testdata/testdata.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyBad.graphql
  pkg/assembler/clients/operations/certifyPkg.graphql
  pkg/assembler/clients/operations/certifyScorecard.graphql
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/hasSourceAt.graphql
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/clients/operations/package.graphql
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/source.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
  pkg/certifier/scorecard/scorecard.go
  pkg/ingestor/parser/vuln/vuln.go
Labels: size/XXL

#636 Improve query performance for verbs / links.
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyPkg.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/path.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
Labels: size/XXL

#638 Default to in-memory backend
  cmd/graphql_playground/cmd/root.go
  cmd/guacone/cmd/root.go
Labels: size/XS

#639 Graphql changes for consistency
  pkg/assembler/graphql/examples/artifact_builder.gql
Labels: size/XS

#646 Update inmem backend to be concurrency-safe.
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/certifyBad.go
  pkg/assembler/backends/inmem/certifyPkg.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isVulnerability.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/graphql/examples/has_slsa.gql
Labels: size/L

#650 Rename CertifyPkg to PkgEqual
  .github/scripts/excluded_from_copyright
  cmd/graphql_playground/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/neo4j/pkgEqual.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/pkgEqual.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/certify_pkg.gql
  pkg/assembler/graphql/examples/pkg_equal.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/pkgEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyPkg.resolvers.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
  pkg/assembler/graphql/schema/pkgEqual.graphql
Labels: size/L

#654 Add deps.dev collector, processor and parser
  Makefile
  go.mod
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/helpers/vcs.go
  pkg/assembler/helpers/vcs_test.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/handler/collector/deps_dev/internal/api.pb.go
  pkg/handler/collector/deps_dev/internal/api.proto
  pkg/handler/collector/deps_dev/internal/api_grpc.pb.go
  pkg/handler/collector/deps_dev/internal/google/api/annotations.pb.go
  pkg/handler/collector/deps_dev/internal/google/api/annotations.proto
  pkg/handler/collector/deps_dev/internal/google/api/http.pb.go
  pkg/handler/collector/deps_dev/internal/google/api/http.proto
  pkg/handler/processor/deps_dev/deps_dev.go
  pkg/handler/processor/deps_dev/deps_dev_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_deps_dev.go
  pkg/handler/processor/guesser/type_deps_dev_test.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/vuln/vuln.go
  pkg/ingestor/parser/vuln/vuln_test.go
Labels: size/XXL

#656 add deps_dev to integration test in CI with token
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
  Makefile
  pkg/certifier/scorecard/scorecardRunner_test.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/M

#657 fix gql examples to make ui gen compile
  pkg/assembler/graphql/examples/certify_good.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/M

#658 add ability to parse identifier strings for PURLs
  pkg/collectsub/collectsub/input/identifier_strings.go
  pkg/collectsub/collectsub/input/identifier_strings_test.go
  pkg/ingestor/parser/common/types.go
Labels: size/M

#659 GetIdentifiers from parsers
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M
