Repository guacsec/guac, pull requests merged in 2023-07, with the labels that each got.

#729 Add support for ingesting VEX documents in the CSAF format
  go.mod
  go.sum
  internal/testing/testdata/exampledata/rhsa-csaf.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/handler/processor/csaf/csaf.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_csaf.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/csaf/parser_csaf_test.go
  pkg/ingestor/parser/parser.go
Labels: size/XXL, needs-review

#911 Add initial nodes for arangoDB backend implementation
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  container_files/guac/guac.yaml
  go.mod
  go.sum
  guac.yaml
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/cli/store.go
Labels: size/XXL

#1028 add missing hasMetadata for arango
  pkg/assembler/backends/arangodb/metadata.go
Labels: size/M

#1027 Remove SBOM annotations
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/ingestor/parser/common/helpers.go
Labels: size/L

#1029 fix lint err around annotations
  pkg/assembler/backends/inmem/hasSBOM.go
Labels: size/XS

#1003 [fix] ingests nouns before verbs for test data
  cmd/guacgql/cmd/ingest.go
  go.mod
  go.sum
Labels: size/XXL

#1031 add docker-compose for arango
  arango.docker-compose.yaml
Labels: size/M

#1032 Implement FIndSoftware for Arango backend
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/search.go
Labels: size/L

#969 Implement search dependent packages + testing (updated)
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XL

#1033 implement PointOfContact in inmem backend
  pkg/assembler/backends/arangodb/contact.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pointOfContact.go
  pkg/assembler/backends/inmem/pointOfContact_test.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/neo4j/contact.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/contact.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/contact.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/contact.resolvers.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/XXL

#1037 Remove annotations from hasSBOM gql example
  pkg/assembler/graphql/examples/has_sbom.gql
Labels: size/XS

#1043 set guacone collect files to ingest doc in parallel with bulk assembler
  cmd/guacone/cmd/files.go
  pkg/assembler/backends/arangodb/backend.go
Labels: size/L

#1047 fix allow for go.googlesource.com to be parsed for VcsToSrc
  pkg/assembler/helpers/vcs.go
  pkg/assembler/helpers/vcs_test.go
  pkg/handler/collector/deps_dev/deps_dev.go
Labels: size/S

#1048 cleanup arango backend, add ingestion of builder, add support for source ingestion for Occurrences, return IDs during ingestion and query
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/builder.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/builder.go
  pkg/assembler/backends/inmem/builder_test.go
  pkg/assembler/backends/inmem/src_test.go
  pkg/assembler/backends/neo4j/builder.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/builder.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/schema/builder.graphql
Labels: size/XXL

#1035 remove unused old nodes (pre 0.1)
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/builder.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
  pkg/assembler/nodes.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/osv/osv_test.go
Labels: size/XXL

#1049 Involve `since_time` for collect-sub entry getting.
  pkg/collectsub/client/mock.go
  pkg/collectsub/collectsub/collectsub.pb.go
  pkg/collectsub/collectsub/collectsub.proto
  pkg/collectsub/collectsub/collectsub_grpc.pb.go
  pkg/collectsub/server/db/db_test.go
  pkg/collectsub/server/db/simpledb/simpledb.go
  pkg/collectsub/server/db/types/db.go
  pkg/collectsub/server/server.go
  pkg/handler/collector/deps_dev/internal/api.pb.go
  pkg/handler/collector/deps_dev/internal/api_grpc.pb.go
Labels: size/S

#1046 Implement HasSLSA predicate case + tests (patchPlanning search method)
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XL

#1060 fix PURL NPE and add OCI heuristic
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
Labels: size/S

#1051 Add ability to add ingestPredicates documents for ingestion
  cmd/guacone/cmd/collect.go
  internal/testing/testdata/exampledata/ingest_predicates.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/assembler_test.go
  pkg/handler/processor/guesser/guesser_test.go
  pkg/handler/processor/guesser/type_ingest_predicates.go
  pkg/handler/processor/guesser/type_ingest_predicates_test.go
  pkg/handler/processor/ingest_predicates/ingest_predicates.go
  pkg/handler/processor/ingest_predicates/ingest_predicates_test.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/ingest_predicates/parser_ingest_predicates.go
  pkg/ingestor/parser/ingest_predicates/parser_ingest_predicates_test.go
Labels: size/XXL

#1052 Ingest and Query vulnerabilities for arango backend
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/cve.go
  pkg/assembler/backends/arangodb/ghsa.go
  pkg/assembler/backends/arangodb/osv.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/cve.go
  pkg/assembler/backends/inmem/cve_test.go
  pkg/assembler/backends/inmem/ghsa.go
  pkg/assembler/backends/inmem/ghsa_test.go
  pkg/assembler/backends/inmem/osv.go
  pkg/assembler/backends/inmem/osv_test.go
  pkg/assembler/backends/neo4j/cve.go
  pkg/assembler/backends/neo4j/ghsa.go
  pkg/assembler/backends/neo4j/osv.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/cve.generated.go
  pkg/assembler/graphql/generated/ghsa.generated.go
  pkg/assembler/graphql/generated/osv.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/cve.resolvers.go
  pkg/assembler/graphql/resolvers/ghsa.resolvers.go
  pkg/assembler/graphql/resolvers/osv.resolvers.go
  pkg/assembler/graphql/schema/cve.graphql
  pkg/assembler/graphql/schema/ghsa.graphql
  pkg/assembler/graphql/schema/osv.graphql
Labels: size/XL

#1021 add support for using Tilt for local development
  .github/workflows/ci.yaml
  .tiltignore
  Tiltfile
  cmd/guaccollect/cmd/root.go
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/root.go
  k8s/k8s.yaml
  k8s/tilt-nats-values.yaml
Labels: size/L

#1070 arango ingest/query scorecard and bulk ingestion
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyScorecard_test.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/neo4j/certifyScorecard.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/helpers/parallel.go
  pkg/assembler/clients/operations/certifyScorecard.graphql
  pkg/assembler/clients/operations/cve.graphql
  pkg/assembler/clients/operations/ghsa.graphql
  pkg/assembler/clients/operations/osv.graphql
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/schema/certifyScorecard.graphql
Labels: size/XXL

#1069 Add PkgEqual and HashEqual predictaes -- testing + code planning
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/L

#1073 feat: allow filtering of CertifyVuln query results based on whether they have vulnerabilities
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/M

#1075 Add PointOfContact predicate ingest
  pkg/assembler/assembler.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/helpers/parallel.go
Labels: size/M

#1079 fixing typo to fix #1078
  demo/workflow/queries.gql
  internal/testing/testdata/exampledata/ingest_predicates.json
  pkg/assembler/assembler.go
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/ui_opts.gql
Labels: size/S

#1081 add ingestion and query of hasSLSA for Arango, remove IngestMaterials
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/builder.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/cve.go
  pkg/assembler/backends/arangodb/ghsa.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/osv.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/hasSLSA.go
  pkg/assembler/backends/neo4j/hasSLSA.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/helpers/parallel.go
  pkg/assembler/clients/operations/artifact.graphql
  pkg/assembler/clients/operations/hasSLSA.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XL

#1080 add guac friends md
  GUAC_FRIENDS.md
Labels: size/S

#1084 Fix typo
  pkg/collectsub/datasource/datasource.go
Labels: size/XS

#1085 update client GQL fragments to public usable by go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyGood.graphql
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/contact.graphql
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/hasSLSA.graphql
  pkg/assembler/clients/operations/hasSourceAt.graphql
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/clients/operations/isVulnerability.graphql
  pkg/assembler/clients/operations/metadata.graphql
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/pkgEqual.graphql
  pkg/assembler/clients/operations/trees.graphql
Labels: size/L

#1076 Add Compose Tarball to Release Workflow
  .github/workflows/release.yaml
  docker-compose.yml
Labels: size/M

#1086 add vex info to VULN cli
  cmd/guacone/cmd/vulnerability.go
Labels: size/M

#1083 Adding check for docker builx toolkit in Makefile to fix#1057
  Makefile
Labels: size/S

#1088 Add PointOfContact predicate to PatchPlanning
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/path.graphql
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/L

#995 Fix Logging in Collectsub Server
  go.mod
  go.sum
  pkg/collectsub/server/server.go
Labels: size/M

#1096 add query for IsOccurrence, isDependency and HasSBOM for Arango backend
  pkg/assembler/backends/arangodb/artifact.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/src.go
Labels: size/XL

#1095 [patchPlanning] Make Parent field in BfsNode into a list
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/L

#1101 [PatchPlanning] Toposort / frontiers
  pkg/guacanalytics/patchPlanning.go
  pkg/guacanalytics/toposort.go
Labels: size/L

#1106 issue-1105 inmem HasSBOM: manage no `hasSBOMSpec` sent
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/hasSBOM_test.go
Labels: size/M
