Repository guacsec/guac, pull requests merged in 2023-12, with the labels that each got.

#1526 Update GUAC roadmap
  ROADMAP.md
Labels: size/M

#1558 Change Keys method in kv interface to Scan
  internal/testing/stablememmap/stablememmap.go
  pkg/assembler/backends/keyvalue/artifact.go
  pkg/assembler/backends/keyvalue/builder.go
  pkg/assembler/backends/keyvalue/certifyBad.go
  pkg/assembler/backends/keyvalue/certifyGood.go
  pkg/assembler/backends/keyvalue/certifyLegal.go
  pkg/assembler/backends/keyvalue/certifyScorecard.go
  pkg/assembler/backends/keyvalue/certifyVEXStatement.go
  pkg/assembler/backends/keyvalue/certifyVuln.go
  pkg/assembler/backends/keyvalue/hasMetadata.go
  pkg/assembler/backends/keyvalue/hasSBOM.go
  pkg/assembler/backends/keyvalue/hasSLSA.go
  pkg/assembler/backends/keyvalue/hasSourceAt.go
  pkg/assembler/backends/keyvalue/hashEqual.go
  pkg/assembler/backends/keyvalue/isDependency.go
  pkg/assembler/backends/keyvalue/isOccurrence.go
  pkg/assembler/backends/keyvalue/license.go
  pkg/assembler/backends/keyvalue/pkg.go
  pkg/assembler/backends/keyvalue/pkgEqual.go
  pkg/assembler/backends/keyvalue/pointOfContact.go
  pkg/assembler/backends/keyvalue/src.go
  pkg/assembler/backends/keyvalue/vulnEqual.go
  pkg/assembler/backends/keyvalue/vulnMetadata.go
  pkg/assembler/backends/keyvalue/vulnerability.go
  pkg/assembler/kv/kv.go
  pkg/assembler/kv/memmap/memmap.go
  pkg/assembler/kv/redis/redis.go
  pkg/assembler/kv/tikv/tikv.go
Labels: size/XL

#1507 Inlcuded a faster fmt
  Makefile
Labels: size/XS

#1563 nix.shell: Bump go to 1.21
  shell.nix
Labels: size/XS

#1564 Feature/update arango hasSBOM adding includes
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/arangodb/pkg.go
  pkg/assembler/backends/arangodb/pkgEqual.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/helper/organize.go
  pkg/assembler/backends/keyvalue/backend.go
  pkg/assembler/backends/keyvalue/hasSBOM.go
  pkg/assembler/backends/keyvalue/isDependency.go
  pkg/assembler/backends/keyvalue/isOccurrence.go
  pkg/assembler/backends/keyvalue/pkg.go
Labels: size/XXL

#1562 Add performance test for redis.
  .github/workflows/db-performance-test.yaml
  Makefile
  container_files/redis.yaml
  container_files/redis/guac.yaml
Labels: size/L

#1578 add guac cooking show to roadmap
  ROADMAP.md
Labels: size/XS

#1580 Remove extra read locking that will cause deadlock.
  pkg/assembler/backends/keyvalue/path.go
Labels: size/XS

#1581 Fix some error returns without unlocks.
  pkg/assembler/backends/keyvalue/pkg.go
  pkg/assembler/backends/keyvalue/src.go
  pkg/assembler/backends/keyvalue/vulnerability.go
Labels: size/M

#1582 fix vulns query not properly evaluating isDependency
  cmd/guacone/cmd/vulnerability.go
  pkg/assembler/helpers/purl_test.go
Labels: size/L

#1579 Add benchmark for TiKV
  .github/workflows/db-performance-test.yaml
  Makefile
  container_files/tikv.yaml
  container_files/tikv/guac.yaml
Labels: size/L

#1585 Enable query on benchmark, fix some Scan() issues in keyvalue
  .github/workflows/db-performance-test.yaml
  pkg/assembler/kv/redis/redis.go
  pkg/assembler/kv/tikv/tikv.go
Labels: size/M

#1584 update deps.dev parser to output hasSBOM
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
Labels: size/L

#1583 Ent: hasSBOM 'included' implementation
  pkg/assembler/backends/ent/artifact.go
  pkg/assembler/backends/ent/artifact/artifact.go
  pkg/assembler/backends/ent/artifact/where.go
  pkg/assembler/backends/ent/artifact_create.go
  pkg/assembler/backends/ent/artifact_query.go
  pkg/assembler/backends/ent/artifact_update.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/helpers_test.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/billofmaterials.go
  pkg/assembler/backends/ent/billofmaterials/billofmaterials.go
  pkg/assembler/backends/ent/billofmaterials/where.go
  pkg/assembler/backends/ent/billofmaterials_create.go
  pkg/assembler/backends/ent/billofmaterials_query.go
  pkg/assembler/backends/ent/billofmaterials_update.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/dependency.go
  pkg/assembler/backends/ent/dependency/dependency.go
  pkg/assembler/backends/ent/dependency/where.go
  pkg/assembler/backends/ent/dependency_create.go
  pkg/assembler/backends/ent/dependency_query.go
  pkg/assembler/backends/ent/dependency_update.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/occurrence.go
  pkg/assembler/backends/ent/occurrence/occurrence.go
  pkg/assembler/backends/ent/occurrence/where.go
  pkg/assembler/backends/ent/occurrence_create.go
  pkg/assembler/backends/ent/occurrence_query.go
  pkg/assembler/backends/ent/occurrence_update.go
  pkg/assembler/backends/ent/packageversion.go
  pkg/assembler/backends/ent/packageversion/packageversion.go
  pkg/assembler/backends/ent/packageversion/where.go
  pkg/assembler/backends/ent/packageversion_create.go
  pkg/assembler/backends/ent/packageversion_query.go
  pkg/assembler/backends/ent/packageversion_update.go
  pkg/assembler/backends/ent/schema/artifact.go
  pkg/assembler/backends/ent/schema/billofmaterials.go
  pkg/assembler/backends/ent/schema/dependency.go
  pkg/assembler/backends/ent/schema/occurrence.go
  pkg/assembler/backends/ent/schema/packageversion.go
Labels: size/XXL

#1586 Ent - Restore IngestPackages concurrently
  pkg/assembler/backends/ent/backend/helpers_test.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/sbom_test.go
Labels: size/M

#1594 Update ent and arango source model generation.
  internal/testing/testdata/models.go
  pkg/assembler/backends/arangodb/src.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/source.go
Labels: size/M

#1593 Ent: IngestOccurrences optimized with concurrently
  pkg/assembler/backends/ent/backend/occurrence.go
Labels: size/S

#1595 Ent: IngestSources optimized with concurrently
  pkg/assembler/backends/ent/backend/source.go
Labels: size/S

#1596 Ent: IngestArtifacts optimized using concurrently
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/backend/artifact_test.go
Labels: size/M

#1598 Ent: fixed lint issue on 'main'
  pkg/assembler/backends/ent/backend/helpers.go
Labels: size/S

#1599 Ent: ingest Builders, CertifyBads, CertifyGoods, CertifyLegals refactored concurrently
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyLegal_test.go
  pkg/assembler/backends/ent/backend/helpers_test.go
Labels: size/L

#1540 fix queryVulnsViaVulnNodeNeighbors to check for certifyVex edges
  cmd/guacone/cmd/vulnerability.go
Labels: size/L

#1605 Update vuln query to utilize hasSBOM and pass in SBOM URI or purl to search
  cmd/guacone/cmd/vulnerability.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/ingestor/parser/common/graph_builder.go
Labels: size/L

#1608 remove check if pkgID has already been checked for recursive vuln query
  cmd/guacone/cmd/vulnerability.go
Labels: size/M
