Repository guacsec/guac, pull requests merged in 2023-09, with the labels that each got.

#1207 Add Legal information schema and inmem backend.
  .github/scripts/excluded_from_copyright
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/helper/validation.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/inmem/certifyLegal.go
  pkg/assembler/backends/inmem/certifyLegal_test.go
  pkg/assembler/backends/inmem/license.go
  pkg/assembler/backends/inmem/license_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/src.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyLegal.graphql
  pkg/assembler/clients/operations/license.graphql
  pkg/assembler/clients/operations/path.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyLegal.generated.go
  pkg/assembler/graphql/generated/license.generated.go
  pkg/assembler/graphql/generated/path.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers.go
  pkg/assembler/graphql/resolvers/license.resolvers.go
  pkg/assembler/graphql/schema/certifyLegal.graphql
  pkg/assembler/graphql/schema/license.graphql
  pkg/assembler/graphql/schema/path.graphql
Labels: size/XXL

#1223 Feature/vuln metadata implementation on arango
  internal/testing/testdata/models.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/certifyVuln_test.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
  pkg/assembler/backends/arangodb/vulnMetadata_test.go
Labels: size/XXL

#1186 Included docstrings for parser_csaf
  pkg/ingestor/parser/csaf/parser_csaf.go
Labels: size/M

#1195 Refactor ingestor code
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/ingestor.go
Labels: size/L

#1227 Feature/vuln equal bulk ingestion and arango updates
  cmd/guacgql/cmd/ingest.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/vulnEqual.go
  pkg/assembler/backends/arangodb/vulnEqual_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/hashEqual.go
  pkg/assembler/backends/inmem/vulnEqual.go
  pkg/assembler/backends/inmem/vulnEqual_test.go
  pkg/assembler/backends/neo4j/vulnEqual.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/vulnEqual.graphql
  pkg/assembler/clients/operations/vulnMetadata.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/vulnEqual.generated.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers_test.go
  pkg/assembler/graphql/schema/vulnEqual.graphql
Labels: size/XXL

#1232 Ent - Dependency management
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/dependency.go
  pkg/assembler/backends/ent/dependency/dependency.go
  pkg/assembler/backends/ent/dependency/where.go
  pkg/assembler/backends/ent/dependency_create.go
  pkg/assembler/backends/ent/dependency_query.go
  pkg/assembler/backends/ent/dependency_update.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/dependency.go
Labels: size/XXL

#1228 update SPDX parser to skip empty and 0 hashes
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#1230 fix: increase gprc max message size
  pkg/collectsub/server/server.go
Labels: size/XS

#1235 Fix inmem unit test.
  pkg/assembler/backends/arangodb/vulnEqual_test.go
  pkg/assembler/backends/inmem/vulnEqual_test.go
Labels: size/XS

#1236 remove helper as unused code from old pre-release assembler
  pkg/assembler/helper.go
  pkg/assembler/helper_test.go
Labels: size/L

#1240 Ent - CertifyVuln: fixed noVuln management
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifyvuln.go
Labels: size/S

#1239 Feature/pkg equals bulk ingestion and arango updates
  cmd/guacgql/cmd/ingest.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/pkgEqual.go
  pkg/assembler/backends/arangodb/pkgEqual_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/inmem/pkgEqual_test.go
  pkg/assembler/backends/neo4j/pkgEqual.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/pkgEqual.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/pkgEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers_test.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers_test.go
  pkg/assembler/graphql/schema/pkgEqual.graphql
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XXL

#1238 Ent - IngestVulnEquals with tests
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnEqual_test.go
Labels: size/L

#1222 Add support for sending encoded documents
  go.mod
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
Labels: size/M

#1243 Ent - IngestPkgEquals with tests
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
Labels: size/L

#1246 Fix/add missing unit tests arango
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyBad_test.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyGood_test.go
  pkg/assembler/backends/arangodb/certifyScorecard_test.go
  pkg/assembler/backends/arangodb/certifyVEXStatement.go
  pkg/assembler/backends/arangodb/certifyVEXStatement_test.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/arangodb/certifyVuln_test.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hasSLSA_test.go
  pkg/assembler/backends/arangodb/hashEqual_test.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isDependency_test.go
  pkg/assembler/backends/arangodb/isOccurrence_test.go
  pkg/assembler/backends/arangodb/pkgEqual.go
  pkg/assembler/backends/arangodb/pkgEqual_test.go
  pkg/assembler/backends/arangodb/vulnEqual.go
  pkg/assembler/backends/arangodb/vulnEqual_test.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
  pkg/assembler/backends/arangodb/vulnMetadata_test.go
  pkg/assembler/backends/arangodb/vulnerability_test.go
Labels: size/XXL

#1245 Improved Runtime of Function Process in process.go
  go.mod
  go.sum
  internal/testing/simpledoc/simpledoc.go
  pkg/handler/processor/process/process.go
Labels: size/S

#1260 Ent - IngestBuilders with tests
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/builders_test.go
Labels: size/L

#1262 Feature/has metadata bulk ingestion and arango updates
  cmd/guacgql/cmd/ingest.go
  internal/testing/mocks/backend.go
  pkg/assembler/assembler.go
  pkg/assembler/assembler_test.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasMetadata.go
  pkg/assembler/backends/arangodb/hasMetadata_test.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
  pkg/assembler/backends/arangodb/vulnMetadata_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/hasMetadata.go
  pkg/assembler/backends/inmem/hasMetadata_test.go
  pkg/assembler/backends/inmem/vulnMetadata.go
  pkg/assembler/backends/inmem/vulnMetadata_test.go
  pkg/assembler/backends/neo4j/hasMetadata.go
  pkg/assembler/backends/neo4j/vulnMetadata.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/metadata.graphql
  pkg/assembler/clients/operations/vulnMetadata.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/metadata.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/metadata.resolvers.go
  pkg/assembler/graphql/resolvers/metadata.resolvers_test.go
  pkg/assembler/graphql/resolvers/vulnMetadata.resolvers.go
  pkg/assembler/graphql/resolvers/vulnMetadata.resolvers_test.go
  pkg/assembler/graphql/schema/metadata.graphql
  pkg/assembler/graphql/schema/vulnMetadata.graphql
Labels: size/XXL

#1249 inmem - PkgEqual: Subpath query filtering
  pkg/assembler/backends/inmem/certifyLegal.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/hasSBOM.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkgEqual.go
  pkg/assembler/backends/inmem/pkgEqual_test.go
Labels: size/L

#1267 guacone - managing totalSuccess
  cmd/guacone/cmd/files.go
  internal/testing/e2e/e2e
Labels: size/XS

#1244 Ingestor/Assembler and SPDX Parser for Legal information.
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler.go
  pkg/assembler/assembler_test.go
  pkg/assembler/backends/inmem/certifyLegal.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/ingestor/parser/common/license.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/XL

#1268 Feature/pointofcontact bulk arango
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasMetadata.go
  pkg/assembler/backends/arangodb/pointOfContact.go
  pkg/assembler/backends/arangodb/pointOfContact_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/pointOfContact.go
  pkg/assembler/backends/inmem/pointOfContact_test.go
  pkg/assembler/backends/neo4j/contact.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/contact.graphql
  pkg/assembler/clients/operations/metadata.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/contact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/contact.resolvers.go
  pkg/assembler/graphql/resolvers/contact.resolvers_test.go
  pkg/assembler/graphql/schema/contact.graphql
Labels: size/XXL

#1269 Update resolvers for legal nodes and add tests.
  pkg/assembler/backends/inmem/certifyLegal.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers_test.go
  pkg/assembler/graphql/resolvers/license.resolvers_test.go
Labels: size/XL

#1264 Fixed CSAF GetIdentifiers
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/csaf/parser_csaf_test.go
Labels: size/M

#1275 Log and continue on ingest errors with bulk assemler.
  pkg/assembler/clients/helpers/bulk.go
Labels: size/M

#1273 add nightly release
  .github/workflows/nightly-release.yaml
  .github/workflows/release.yaml
  .goreleaser-nightly.yaml
Labels: size/L

#1271 Ent - IngestScorecards implementation with tests
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/scorecard_test.go
Labels: size/L

#1285 Backend interface - Methods for returning 'string'
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/backend.go
  pkg/assembler/backends/neo4j/backend.go
Labels: size/M

#1283 Ent - Bump v0.12.4-0.20230918073025-797534a0d1ca
  .github/workflows/ci.yaml
  go.mod
  go.sum
  pkg/assembler/backends/ent/artifact_create.go
  pkg/assembler/backends/ent/billofmaterials_create.go
  pkg/assembler/backends/ent/builder_create.go
  pkg/assembler/backends/ent/certification_create.go
  pkg/assembler/backends/ent/certifyscorecard_create.go
  pkg/assembler/backends/ent/certifyvex_create.go
  pkg/assembler/backends/ent/certifyvuln_create.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/dependency_create.go
  pkg/assembler/backends/ent/hashequal_create.go
  pkg/assembler/backends/ent/hassourceat_create.go
  pkg/assembler/backends/ent/isvulnerability_create.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/occurrence_create.go
  pkg/assembler/backends/ent/packagename_create.go
  pkg/assembler/backends/ent/packagenamespace_create.go
  pkg/assembler/backends/ent/packagetype_create.go
  pkg/assembler/backends/ent/packageversion_create.go
  pkg/assembler/backends/ent/pkgequal_create.go
  pkg/assembler/backends/ent/runtime/runtime.go
  pkg/assembler/backends/ent/scorecard_create.go
  pkg/assembler/backends/ent/slsaattestation_create.go
  pkg/assembler/backends/ent/sourcename_create.go
  pkg/assembler/backends/ent/sourcenamespace_create.go
  pkg/assembler/backends/ent/sourcetype_create.go
  pkg/assembler/backends/ent/vulnequal_create.go
  pkg/assembler/backends/ent/vulnerabilityid_create.go
  pkg/assembler/backends/ent/vulnerabilitytype_create.go
Labels: size/S

#1281 Feature/ hasSourceAt bulk inmem and arango implementation
  cmd/guacgql/cmd/ingest.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/hasSourceAt.go
  pkg/assembler/backends/arangodb/hasSourceAt_test.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/hasSourceAt.go
  pkg/assembler/backends/inmem/hasSourceAt_test.go
  pkg/assembler/backends/neo4j/hasSourceAt.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/operations/hasSourceAt.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers_test.go
  pkg/assembler/graphql/schema/hasSourceAt.graphql
  pkg/guacanalytics/patchPlanning_test.go
Labels: size/XXL

#1280 Changed make fmt to ignore .git files
  Makefile
Labels: size/XS

#1284 use officially released go-vex dependency v0.2.1
  go.mod
  go.sum
Labels: size/XS

#1294 use github app token to trigger nightly release
  .github/workflows/nightly-release.yaml
Labels: size/S

#1295 Ent - IngestCertifyGoods and IngestCertifyBads
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certify_test.go
Labels: size/XL

#1241 Implemented OpenVEX
  README.md
  internal/testing/testdata/exampledata/open-vex-affected.json
  internal/testing/testdata/exampledata/open-vex-not-affected.json
  internal/testing/testdata/testdata.go
  pkg/handler/processor/guesser/type_open_vex.go
  pkg/handler/processor/guesser/type_open_vex_test.go
  pkg/handler/processor/open_vex/open_vex.go
  pkg/handler/processor/open_vex/open_vex_test.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/open_vex/parser_open_vex.go
  pkg/ingestor/parser/open_vex/parser_open_vex_test.go
Labels: size/XL

#1296 Enable GitHub CI tests
  .github/workflows/ci.yaml
  go.mod
  go.sum
  internal/testing/mocks/backend.go
  pkg/assembler/backends/ent/artifact_create.go
  pkg/assembler/backends/ent/billofmaterials_create.go
  pkg/assembler/backends/ent/builder_create.go
  pkg/assembler/backends/ent/certification_create.go
  pkg/assembler/backends/ent/certifyscorecard_create.go
  pkg/assembler/backends/ent/certifyvex_create.go
  pkg/assembler/backends/ent/certifyvuln_create.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/dependency_create.go
  pkg/assembler/backends/ent/hashequal_create.go
  pkg/assembler/backends/ent/hassourceat_create.go
  pkg/assembler/backends/ent/isvulnerability_create.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/occurrence_create.go
  pkg/assembler/backends/ent/packagename_create.go
  pkg/assembler/backends/ent/packagenamespace_create.go
  pkg/assembler/backends/ent/packagetype_create.go
  pkg/assembler/backends/ent/packageversion_create.go
  pkg/assembler/backends/ent/pkgequal_create.go
  pkg/assembler/backends/ent/runtime/runtime.go
  pkg/assembler/backends/ent/scorecard_create.go
  pkg/assembler/backends/ent/slsaattestation_create.go
  pkg/assembler/backends/ent/sourcename_create.go
  pkg/assembler/backends/ent/sourcenamespace_create.go
  pkg/assembler/backends/ent/sourcetype_create.go
  pkg/assembler/backends/ent/vulnequal_create.go
  pkg/assembler/backends/ent/vulnerabilityid_create.go
  pkg/assembler/backends/ent/vulnerabilitytype_create.go
Labels: size/S

#1303 fix bug in hasSLSA for arango
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hasSLSA_test.go
Labels: size/L

#1300 Ent - IngestArtifactID,IngestArtifactIDs implementations
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/backend/artifact_test.go
  pkg/assembler/backends/ent/backend/certify_test.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/neighbors_test.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/ent/backend/search_test.go
  pkg/assembler/backends/ent/backend/slsa_test.go
  pkg/assembler/backends/ent/backend/software_test.go
  pkg/assembler/backends/ent/backend/vex_test.go
Labels: size/M

#1270 Ent - upsertPackageIDDoNothing vs upsertPackageIDIgnore
  pkg/assembler/backends/ent/backend/package.go
Labels: size/M

#1299 Ent - IngestHasSourceAts implementation
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/source_test.go
Labels: size/L

#1302 update docker manifest name in nightly releases
  .goreleaser-nightly.yaml
Labels: size/XS

#1305 Confusing name of field in IsDependency GraphQL
  cmd/guacone/cmd/vulnerability.go
  demo/graphql/queries.gql
  demo/workflow/queries.gql
  internal/testing/e2e/expectIsDependencyQ1.json
  internal/testing/e2e/expectIsDependencyQ2.json
  internal/testing/e2e/expectPathPy.json
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isDependency_test.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isDependency_test.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/guacanalytics/patchPlanning.go
Labels: size/XXL

#1304 Ent - IngestHashEquals implementation
  pkg/assembler/backends/ent/backend/hashequal.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
Labels: size/L

#1306 Fixed breaking change by bumping openVex to new release
  go.mod
  go.sum
  internal/testing/testdata/exampledata/open-vex-affected.json
  internal/testing/testdata/exampledata/open-vex-not-affected.json
  pkg/ingestor/parser/open_vex/parser_open_vex.go
Labels: size/M

#1307 fix/openvex
  internal/testing/testdata/testdata.go
  pkg/handler/processor/guesser/type_guesser.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/parser/open_vex/parser_open_vex.go
  pkg/ingestor/parser/parser.go
Labels: size/S

#1311 psuedopause nightly release for now
  .github/workflows/nightly-release.yaml
Labels: size/XS

#1323 Clarify vote needed for Reviewer promotion.
  CONTRIBUTING.md
Labels: size/XS

#1325 update maintainers (-rgreinho)
  MAINTAINERS
Labels: size/XS

#1327 Reviewers list - mrizzi
  CONTRIBUTING.md
Labels: size/XS

#1274 add NoVuln node to ingestion when a package isn't affected
  internal/testing/testdata/exampledata/rhsa-csaf.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/csaf/parser_csaf.go
Labels: size/M

#1328 Ent - IngestOccurrences implementation
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
Labels: size/L

#1309 OSV certifier: bulk ingest
  cmd/guacone/cmd/osv.go
  pkg/ingestor/ingestor.go
Labels: size/M

#1321 Ent - CertifyLegal endpoints implementation
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyLegal_test.go
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/backend/vulnEqual_test.go
  pkg/assembler/backends/ent/certifylegal.go
  pkg/assembler/backends/ent/certifylegal/certifylegal.go
  pkg/assembler/backends/ent/certifylegal/where.go
  pkg/assembler/backends/ent/certifylegal_create.go
  pkg/assembler/backends/ent/certifylegal_delete.go
  pkg/assembler/backends/ent/certifylegal_query.go
  pkg/assembler/backends/ent/certifylegal_update.go
  pkg/assembler/backends/ent/client.go
  pkg/assembler/backends/ent/ent.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/gql_node.go
  pkg/assembler/backends/ent/gql_pagination.go
  pkg/assembler/backends/ent/hook/hook.go
  pkg/assembler/backends/ent/license.go
  pkg/assembler/backends/ent/license/license.go
  pkg/assembler/backends/ent/license/where.go
  pkg/assembler/backends/ent/license_create.go
  pkg/assembler/backends/ent/license_query.go
  pkg/assembler/backends/ent/license_update.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/predicate/predicate.go
  pkg/assembler/backends/ent/schema/certifylegal.go
  pkg/assembler/backends/ent/schema/license.go
  pkg/assembler/backends/ent/tx.go
  pkg/assembler/backends/helper/conversion.go
Labels: size/XXL

#1322 Remove version name from compose tarball.
  .github/workflows/release.yaml
Labels: size/XS

#1330 Ent - Packages: subpath query issue
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/package_test.go
Labels: size/S

#1297 Add support for additional checksums and lower tolerance for tests
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L
