Repository guacsec/guac, pull requests merged in 2023-11, with the labels that each got.

#1329 Ent - IngestBuilderID, IngestPackageID, IngestSourceID, IngestVulnerabilityID
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/builders_test.go
  pkg/assembler/backends/ent/backend/certifyVuln_test.go
  pkg/assembler/backends/ent/backend/certify_test.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/neighbors.go
  pkg/assembler/backends/ent/backend/neighbors_test.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/package_test.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
  pkg/assembler/backends/ent/backend/sbom_test.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/scorecard_test.go
  pkg/assembler/backends/ent/backend/search_test.go
  pkg/assembler/backends/ent/backend/slsa_test.go
  pkg/assembler/backends/ent/backend/software_test.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/source_test.go
  pkg/assembler/backends/ent/backend/vulnEqual_test.go
  pkg/assembler/backends/ent/backend/vulnerability.go
  pkg/assembler/backends/ent/backend/vulnerability_test.go
Labels: size/XL

#1451 Fixed docker-compose down
  docker-compose.yml
Labels: size/XS

#1458 Ent - HasMetadata: applied concurrent approach
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hasMetadata_test.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/hasmetadata.go
Labels: size/M

#1470 Ent - IngestHasSbomID
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/sbom_test.go
Labels: size/M

#1469 Ent - ScorecardID IngestScorecardID
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/scorecard_test.go
Labels: size/M

#1471 fix go sum based on dependabot changes on main
  go.sum
Labels: size/XS

#1457 add workflow to test ingestion/query performance for backends
  .github/workflows/db-performance-test.yaml
  .github/workflows/reusable-local-build.yaml
  Makefile
  container_files/arango.yaml
  container_files/ent.yaml
  container_files/mem.yaml
  container_files/neo4j.yaml
Labels: size/L

#1459 Ent - Vulnerability endpoints: applied concurrent approach
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement_test.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/helpers_test.go
  pkg/assembler/backends/ent/backend/vulnEqual_test.go
  pkg/assembler/backends/ent/backend/vulnerability.go
  pkg/assembler/backends/ent/backend/vulnerability_test.go
Labels: size/L

#1453 fix check for ingested packages and source IDs
  pkg/assembler/graphql/helpers/package.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
Labels: size/XS

#1474 change to workflow_dispatch to manually trigger performance tests
  .github/workflows/db-performance-test.yaml
Labels: size/S

#1473 Ent - PkgEqualsID
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/pkgequal_test.go
Labels: size/M

#1478 Ent: error management when closing Ent client during tests
  go.mod
  go.sum
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/neighbors_test.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/package_test.go
  pkg/assembler/backends/ent/backend/search_test.go
  pkg/assembler/backends/ent/backend/software_test.go
  pkg/assembler/backends/ent/testutils/suite.go
Labels: size/XL

#1485 OCI purl: fix repository URL management
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
Labels: size/XS

#1501 Fixed Error in Scorecard Certifier
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
Labels: size/M

#1452 Implemented the REST API
  .github/scripts/excluded_from_copyright
  .goreleaser.yaml
  cmd/README.md
  cmd/guacrest/README.md
  cmd/guacrest/bad.go
  cmd/guacrest/bad_test.go
  cmd/guacrest/design.md
  cmd/guacrest/docs/docs.go
  cmd/guacrest/docs/swagger.json
  cmd/guacrest/docs/swagger.yaml
  cmd/guacrest/known.go
  cmd/guacrest/known_test.go
  cmd/guacrest/main.go
  cmd/guacrest/vulnerability.go
  cmd/guacrest/vulnerability_test.go
  go.mod
  go.sum
Labels: size/XXL

#1514 Update all resolvers for Return ID
  pkg/assembler/backends/backends.go
  pkg/assembler/graphql/helpers/package.go
  pkg/assembler/graphql/helpers/package_test.go
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/builder.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers_test.go
  pkg/assembler/graphql/resolvers/contact.resolvers.go
  pkg/assembler/graphql/resolvers/contact.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers_test.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers_test.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers_test.go
  pkg/assembler/graphql/resolvers/license.resolvers.go
  pkg/assembler/graphql/resolvers/license.resolvers_test.go
  pkg/assembler/graphql/resolvers/metadata.resolvers.go
  pkg/assembler/graphql/resolvers/metadata.resolvers_test.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers.go
  pkg/assembler/graphql/resolvers/source.resolvers.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers_test.go
  pkg/assembler/graphql/resolvers/vulnerability.resolvers.go
Labels: size/L

#1498 add openssf scorecard badge for guac
  README.md
Labels: size/XS

#1529 Feature/1116 arango verb mutation
  pkg/assembler/backends/arangodb/artifact_test.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/builder_test.go
  pkg/assembler/backends/arangodb/certifyBad.go
  pkg/assembler/backends/arangodb/certifyBad_test.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyGood_test.go
  pkg/assembler/backends/arangodb/certifyLegal.go
  pkg/assembler/backends/arangodb/certifyLegal_test.go
  pkg/assembler/backends/arangodb/certifyScorecard.go
  pkg/assembler/backends/arangodb/certifyScorecard_test.go
  pkg/assembler/backends/arangodb/certifyVEXStatement.go
  pkg/assembler/backends/arangodb/certifyVEXStatement_test.go
  pkg/assembler/backends/arangodb/certifyVuln.go
  pkg/assembler/backends/arangodb/certifyVuln_test.go
  pkg/assembler/backends/arangodb/hasMetadata.go
  pkg/assembler/backends/arangodb/hasMetadata_test.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
  pkg/assembler/backends/arangodb/hasSLSA.go
  pkg/assembler/backends/arangodb/hasSLSA_test.go
  pkg/assembler/backends/arangodb/hasSourceAt.go
  pkg/assembler/backends/arangodb/hasSourceAt_test.go
  pkg/assembler/backends/arangodb/hashEqual.go
  pkg/assembler/backends/arangodb/hashEqual_test.go
  pkg/assembler/backends/arangodb/isDependency.go
  pkg/assembler/backends/arangodb/isDependency_test.go
  pkg/assembler/backends/arangodb/isOccurrence.go
  pkg/assembler/backends/arangodb/isOccurrence_test.go
  pkg/assembler/backends/arangodb/license_test.go
  pkg/assembler/backends/arangodb/path_test.go
  pkg/assembler/backends/arangodb/pkgEqual.go
  pkg/assembler/backends/arangodb/pkgEqual_test.go
  pkg/assembler/backends/arangodb/pkg_test.go
  pkg/assembler/backends/arangodb/pointOfContact.go
  pkg/assembler/backends/arangodb/pointOfContact_test.go
  pkg/assembler/backends/arangodb/search_test.go
  pkg/assembler/backends/arangodb/src_test.go
  pkg/assembler/backends/arangodb/vulnEqual.go
  pkg/assembler/backends/arangodb/vulnEqual_test.go
  pkg/assembler/backends/arangodb/vulnMetadata.go
  pkg/assembler/backends/arangodb/vulnMetadata_test.go
  pkg/assembler/backends/arangodb/vulnerability_test.go
Labels: size/XXL

#1528 CSAF Parser: fixed branches' names collision
  internal/testing/testdata/exampledata/rhsa-csaf.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/csaf/parser_csaf_test.go
Labels: size/M

#1536 Complete Ent Return -ID
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyLegal_test.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement_test.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/certifyVuln_test.go
  pkg/assembler/backends/ent/backend/certify_test.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/dependency_test.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hasMetadata_test.go
  pkg/assembler/backends/ent/backend/hashequal.go
  pkg/assembler/backends/ent/backend/hashequal_test.go
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/backend/license_test.go
  pkg/assembler/backends/ent/backend/notimplemented.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/occurrence_test.go
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/pointOfContact_test.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/slsa_test.go
  pkg/assembler/backends/ent/backend/software_test.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/source_test.go
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnEqual_test.go
Labels: size/L

#1509 Iterating Over all IDs in QueryVulnsViaVulnNodeNeighbors
  cmd/guacone/cmd/vulnerability.go
Labels: size/M

#1543 Fix single target build and remove unused function from test
  .goreleaser.yaml
  pkg/assembler/backends/keyvalue/hasSBOM_test.go
Labels: size/S
