Repository guacsec/guac, pull requests merged in 2023-06, with the labels that each got.

#918 build multi-arch bins and container images
  .github/workflows/release.yaml
  .gitignore
  .goreleaser.yaml
  dockerfiles/Dockerfile.goreleaser
Labels: size/L

#908 Update spdx and osv libraries.
  go.mod
  go.sum
  pkg/handler/processor/guesser/type_spdx.go
  pkg/handler/processor/spdx/spdx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M

#919 use POSIX compliant way to redirect file descriptors in Makefile
  Makefile
Labels: size/XS

#923 fix time equal check bug in certifyVuln and ensure that other match in the inmem database
  pkg/assembler/backends/inmem/certifyScorecard.go
  pkg/assembler/backends/inmem/certifyVEXStatement.go
  pkg/assembler/backends/inmem/certifyVuln.go
  pkg/assembler/backends/inmem/hasSourceAt.go
Labels: size/XS

#924 add support for 'githubactions' package types
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
Labels: size/XS

#926 Remove DoesRangeInclude error testing
  pkg/misc/depversion/depversion.go
  pkg/misc/depversion/depversion_test.go
Labels: size/S

#927 Changed build tag to separate scorecardRunner_test.go to run only on…
  pkg/certifier/scorecard/scorecardRunner_test.go
Labels: size/XS

#928 fix deps.dev unit test
  internal/testing/testdata/testdata.go
Labels: size/XS

#907 Included tests and handled stack overflow error for parser
  .github/scripts/excluded_from_copyright
  internal/testing/mocks/documentparser.go
  internal/testing/mocks/mockgen.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
Labels: size/L

#901 feat: add environment file for configuring docker compose
  .env
  docker-compose.yml
  internal/testing/testdata/testdata.go
Labels: size/S, needs-review

#940 Enable tracing of GraphQL requests
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  go.mod
  go.sum
  pkg/cli/store.go
Labels: size/S

#944 use docker compose healthcheck
  .env
  Makefile
  docker-compose.yml
  dockerfiles/Dockerfile.guac-cont
  dockerfiles/Dockerfile.healthcheck
Labels: size/L

#945 use goreleaser for local builds
  .goreleaser.yaml
  Makefile
  dockerfiles/Dockerfile.goreleaser
  dockerfiles/Dockerfile.guac-cont
Labels: size/M

#947 fix docker build and check for goreleaser
  Makefile
  dockerfiles/Dockerfile.goreleaser
Labels: size/XS

#946 Fixed: Stackoverflow in internal/testing/dochelper
  internal/testing/dochelper/dochelper.go
  internal/testing/dochelper/dochelper_test.go
Labels: size/L

#959 use current docker context of host for buildx
  .goreleaser.yaml
  Makefile
Labels: size/XS

#960 add docker context for snapshot and release build
  .github/workflows/release.yaml
Labels: size/XS

#961 fix: logging typo
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
Labels: size/XS

#968 special case for arch x86_64 should be converted to amd64 for GOARCH …
  Makefile
Labels: size/XS

#962 moved vcs.go and vcs_test.go to misc
  pkg/assembler/helpers/vcs.go
  pkg/handler/collector/github/github.go
Labels: size/M

#989 feat(collector): expose Google Cloud Storage collector from guacone CLI
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/gcs_test.go
  pkg/cli/store.go
  pkg/handler/collector/gcs/gcs.go
  pkg/handler/collector/gcs/gcs_test.go
Labels: size/L

#992 added error if CycloneDX sboms are missing top level metadata fields
  internal/testing/testdata/exampledata/cyclonedx-no-top-level.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#994 fix(Makefile): make container
  Makefile
Labels: size/XS

#979 getTopLevelPackage will now check DESCRIBES and DESCRIBED_BY relation…
  go.mod
  go.sum
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#997 update spdx parsing and check for spdxIdentifier==DOCUMENT
  internal/testing/testdata/exampledata/invalid-spdx-identifier-spdx.json
  internal/testing/testdata/testdata.go
  pkg/handler/processor/guesser/type_spdx.go
  pkg/handler/processor/spdx/spdx.go
  pkg/handler/processor/spdx/spdx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#978 add GUAC use cases
  README.md
  use-cases.md
Labels: size/M

#998 Add search gql
  .github/scripts/excluded_from_copyright
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/search.go
  pkg/assembler/backends/neo4j/search.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/search.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/search.resolvers.go
  pkg/assembler/graphql/schema/search.graphql
Labels: size/L

#999 Implement batch ingestion for packages, artifacts, isDependency and isOccurrences
  cmd/guacgql/cmd/ingest.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/inmem/artifact.go
  pkg/assembler/backends/inmem/artifact_test.go
  pkg/assembler/backends/inmem/isDependency.go
  pkg/assembler/backends/inmem/isDependency_test.go
  pkg/assembler/backends/inmem/isOccurrence.go
  pkg/assembler/backends/inmem/isOccurrence_test.go
  pkg/assembler/backends/inmem/pkg.go
  pkg/assembler/backends/inmem/pkg_test.go
  pkg/assembler/backends/neo4j/artifact.go
  pkg/assembler/backends/neo4j/isDependency.go
  pkg/assembler/backends/neo4j/isOccurrence.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/clients/helpers/parallel.go
  pkg/assembler/clients/operations/artifact.graphql
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/clients/operations/package.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/artifact.resolvers.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/schema/artifact.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
  pkg/assembler/graphql/schema/package.graphql
Labels: size/XL
