Repository guacsec/guac, pull requests merged in 2024-10, with the labels that each got.

#2153 Search for Vulns via Artifact
  cmd/guacone/cmd/vulnerability.go
  pkg/guacanalytics/searchForSBOM.go
Labels: size/L

#2156 CycloneDX SBOM: support nested components
  internal/testing/testdata/exampledata/cyclonedx-components-flat.json
  internal/testing/testdata/exampledata/cyclonedx-components-nested.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#2164 if LicenseRef is specified without an inline do not create a license node
  internal/testing/testdata/exampledata/small-legal-cyclonedx-no-inline.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/clearlydefined/clearlydefined.go
  pkg/ingestor/parser/common/license.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/XL

#2163 update certifier with specific package queries to keep state
  cmd/guaccollect/cmd/license.go
  cmd/guaccollect/cmd/osv.go
  cmd/guacone/cmd/license.go
  cmd/guacone/cmd/osv.go
  container_files/arango/guac.yaml
  container_files/ent/guac.yaml
  container_files/guac/guac.yaml
  container_files/neo4j/guac.yaml
  container_files/redis/guac.yaml
  container_files/tikv/guac.yaml
  guac.yaml
  internal/testing/backend/main_test.go
  internal/testing/backend/search_test.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/assembler/backends/neo4j/search.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/search.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/search.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/search.resolvers.go
  pkg/assembler/graphql/schema/search.graphql
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/cli/store.go
Labels: size/XXL

#2166 LicenseInputSpec: do not add 'ListVersion' with 'Inline'
  pkg/ingestor/parser/common/license.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/S

#2167 add comment on certifier when last-scan is set or not set
  pkg/certifier/components/root_package/root_package.go
Labels: size/S

#2181 [ENT] add direct subject queries for verbs
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/concurrently.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/helpers.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/vulnMetadata.go
Labels: size/L

#2183 Fix CD discovered license link in gql generated docs
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyLegal.graphql
Labels: size/S

#2184 fix issues with certifier querying running into postgres parameter limit
  internal/testing/backend/search_test.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/ent/backend/helpers.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/assembler/backends/neo4j/search.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/search.graphql
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/search.resolvers.go
  pkg/assembler/graphql/schema/search.graphql
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/ingestor/parser/common/scanner/scanner.go
Labels: size/XL

#2193 Fix: missing null check in certifyLegal blobstore backend
  pkg/assembler/backends/keyvalue/certifyLegal.go
Labels: size/XS

#2191 fix ite6 vuln attestation to use the right predicatetype
  internal/testing/testdata/exampledata/certify-novuln.json
  internal/testing/testdata/exampledata/certify-vuln.json
  internal/testing/testdata/testdata.go
  pkg/certifier/attestation/attestation_vuln.go
  pkg/handler/processor/guesser/type_ite6.go
  pkg/ingestor/parser/vuln/vuln.go
Labels: size/S

#2189 Fix Flaky E2e Test
  internal/testing/e2e/e2e
Labels: size/XS

#2168 Add ClearlyDefined to e2e test
  demo/graphql/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectCertifyLegalQ1.json
Labels: size/M

#2200 update batch size on clearly defined and fix bug that when ingesting licenses
  cmd/guaccollect/cmd/license.go
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/ingestor/parser/common/scanner/scanner.go
Labels: size/S

#2201 update queries to hit index
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/sbom.go
Labels: size/XS

#2203 add vulnerability ID index on certifyVuln
  pkg/assembler/backends/ent/migrate/migrations/20241017140224_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifyvuln.go
Labels: size/XS

#2207 fix #2206 add http handler to display version string
  cmd/guacgql/cmd/server.go
  cmd/guacgql/cmd/server_test.go
Labels: size/M

#2194 update vuln attestation to (opiniatedly) follow intoto/vulns v0.1 spec
  internal/testing/dochelper/dochelper.go
  internal/testing/testdata/exampledata/certify-novuln.json
  internal/testing/testdata/exampledata/certify-vuln.json
  internal/testing/testdata/testdata.go
  pkg/certifier/attestation/license/attestation_license.go
  pkg/certifier/attestation/vuln/attestation_vuln.go
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
  pkg/ingestor/parser/clearlydefined/clearlydefined.go
  pkg/ingestor/parser/vuln/vuln.go
Labels: size/L

#2205 change hasSBOMList to add filter based on client usage
  internal/testing/backend/hasSBOM_test.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/helper/preloads.go
  pkg/assembler/backends/helper/preloads_test.go
  pkg/assembler/backends/keyvalue/hasSBOM.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neo4j/pkg.go
  pkg/assembler/backends/neo4j/src.go
Labels: size/XL

#2218 Add vulnerability and License batch querying
  internal/testing/backend/certifyLegal_test.go
  internal/testing/backend/certifyVuln_test.go
  internal/testing/backend/main_test.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/schema/packageversion.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/assembler/backends/neo4j/search.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers.go
  pkg/assembler/graphql/schema/certifyLegal.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/L

#2221 Add IsDependency batch querying
  internal/testing/backend/isDependency_test.go
  internal/testing/backend/main_test.go
  internal/testing/mocks/backend.go
  pkg/assembler/backends/arangodb/search.go
  pkg/assembler/backends/backends.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/assembler/backends/neo4j/search.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers.go
  pkg/assembler/graphql/schema/isDependency.graphql
Labels: size/L

#2249 SPDX 'GENERATED_FROM' and 'GENERATES' management
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#2246 improve batch query
  internal/testing/backend/certifyLegal_test.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/migrate/migrations/20241030212025_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifylegal.go
  pkg/assembler/backends/ent/schema/certifyvuln.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/schema/certifyLegal.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/L
