Repository guacsec/guac, pull requests merged in 2024-06, with the labels that each got.

#1940 fix generate code for linter and static checks
  pkg/assembler/clients/generated/operations.go
Labels: size/XS

#1941 GraphQL - Expose client queries
  .github/PULL_REQUEST_TEMPLATE.md
  cmd/guacone/cmd/bad.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/artifact.graphql
  pkg/assembler/clients/operations/builder.graphql
  pkg/assembler/clients/operations/certifyBad.graphql
  pkg/assembler/clients/operations/certifyGood.graphql
  pkg/assembler/clients/operations/certifyLegal.graphql
  pkg/assembler/clients/operations/certifyScorecard.graphql
  pkg/assembler/clients/operations/certifyVEXStatement.graphql
  pkg/assembler/clients/operations/contact.graphql
  pkg/assembler/clients/operations/hasSourceAt.graphql
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/isDependency.graphql
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/clients/operations/license.graphql
  pkg/assembler/clients/operations/metadata.graphql
  pkg/assembler/clients/operations/pkgEqual.graphql
  pkg/assembler/clients/operations/source.graphql
  pkg/assembler/clients/operations/vulnEqual.graphql
  pkg/assembler/clients/operations/vulnMetadata.graphql
Labels: size/XXL

#1948 Add nil checks for pkgConn and PackagesList
  pkg/certifier/components/root_package/root_package.go
Labels: size/XS

#1950 fix flag initialization and naming
  cmd/guaccollect/cmd/osv.go
  cmd/guaccollect/cmd/root.go
  cmd/guaccollect/cmd/scorecard.go
  guac.yaml
  pkg/cli/store.go
Labels: size/M

#1951 add missing csub-tls flags for guaccollect
  cmd/guaccollect/cmd/root.go
Labels: size/XS

#1963 Adds vulnerability scanning on ingestion
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/gcs_test.go
  cmd/guacone/cmd/github.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/s3.go
  cmd/guacone/cmd/scorecard.go
  cmd/guacone/cmd/vulnerability.go
  guac.yaml
  internal/testing/cmd/ingest/cmd/example.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
  pkg/cli/store.go
  pkg/ingestor/ingestor.go
  pkg/ingestor/parser/common/graph_builder.go
  pkg/ingestor/parser/common/scanner/scanner.go
  pkg/ingestor/parser/common/scanner/scanner_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
  pkg/ingestor/parser/vuln/vuln.go
Labels: size/XL

#1932 Support direct connections to ent from the rest api
  cmd/guacrest/cmd/root.go
  cmd/guacrest/cmd/server.go
  pkg/assembler/backends/ent/backend/migrations.go
  pkg/cli/store.go
  pkg/guacrest/helpers/artifact_test.go
  pkg/guacrest/server/ent.go
Labels: size/L

#1967 Expose certifier and deps.dev batch size and add optional latency (defaults to none)
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/osv.go
  cmd/guaccollect/cmd/scorecard.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  container_files/guac/guac.yaml
  guac.yaml
  internal/testing/cmd/pubsub_test/cmd/osv.go
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
  pkg/cli/store.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/L

#1975 Move to OpenSSF mail server
  README.md
Labels: size/XS

#1935 Add a diff version of the proposal in governance#8
  CONTRIBUTING.md
Labels: size/S

#1986 Fix Google Container Registry URL typo
  internal/testing/testdata/testdata.go
Labels: size/XS
