Repository guacsec/guac, pull requests merged in 2024-01, with the labels that each got.

#1610 [#1405] Feature/query filter
  cmd/guacgql/cmd/server.go
  demo/graphql/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectArtifactsQ1.json
  internal/testing/mocks/resolvers.go
  internal/testing/testdata/models.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/builder.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyGood.generated.go
  pkg/assembler/graphql/generated/certifyLegal.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/contact.generated.go
  pkg/assembler/graphql/generated/directive.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/license.generated.go
  pkg/assembler/graphql/generated/metadata.generated.go
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/pkgEqual.generated.go
  pkg/assembler/graphql/generated/prelude.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/source.generated.go
  pkg/assembler/graphql/generated/vulnEqual.generated.go
  pkg/assembler/graphql/generated/vulnMetadata.generated.go
  pkg/assembler/graphql/generated/vulnerability.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/directive.resolver.go
  pkg/assembler/graphql/resolvers/directive.resolver_test.go
  pkg/assembler/graphql/schema/directive.graphql
Labels: size/L

#1611 feature[add query-for-package-url] inital commit
  demo/graphql/queries.gql
  internal/testing/e2e/expectIsDependencyQ2.json
  internal/testing/e2e/expectPathPy.json
  internal/testing/e2e/expectPkgQ3.json
  internal/testing/e2e/expectPkgQ4.json
  pkg/assembler/graphql/generated/package.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/gqlgen.yml
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/resolvers/package.resolver_test.go
  pkg/assembler/graphql/resolvers/package.resolvers.go
  pkg/assembler/graphql/schema/package.graphql
  pkg/assembler/helpers/namespaces.resolver_test.go
  pkg/assembler/helpers/namspaces.resolver.go
Labels: size/L

#1609 Add concurrency to arango hasSBOM query
  cmd/guacone/cmd/vulnerability.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/arangodb/hasSBOM_test.go
Labels: size/XXL

#1618 Query fIlter support for nested keys
  demo/graphql/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectPkgQ9.json
  internal/testing/testdata/models.go
  pkg/assembler/graphql/resolvers/directive.resolver.go
  pkg/assembler/graphql/resolvers/filterDirective.resolver.go
  pkg/assembler/graphql/resolvers/filterDirective.resolver_test.go
Labels: size/XL

#1627 Fix some logic errors on IsDependency
  pkg/assembler/backends/keyvalue/isDependency.go
  pkg/assembler/backends/keyvalue/pkg.go
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/packages.gql
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/M

#1628 add Contributor Covenant v2.1
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
Labels: size/L

#1631 Add comment for id field on PkgSpec
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/package.graphql
Labels: size/XS

#1629 fix broken link on governance
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: size/L

#1634 expose isDep query
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/artifact.graphql
  pkg/assembler/clients/operations/isDependency.graphql
Labels: size/S

#1632 Add comment on Edge schema to note that edges are bidirectional
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/path.graphql
Labels: size/XS

#1643 fix lint issue on arango hasSBOM
  pkg/assembler/backends/arangodb/hasSBOM_test.go
Labels: size/L

#1645 remove s3 from guacone until further testing is done on the collector
  cmd/guacone/cmd/s3.go
Labels: size/XS

#1646 fix bug where duplicate certifyVuln values showed on output
  cmd/guacone/cmd/vulnerability.go
Labels: size/M

#1472 Encoding guesser
  internal/testing/testdata/exampledata/busybox-cyclonedx.json.zst
  internal/testing/testdata/testdata.go
  pkg/handler/processor/guesser/encoding_guesser.go
  pkg/handler/processor/guesser/encoding_guesser_test.go
  pkg/handler/processor/process/process.go
Labels: size/L, needs-review

#1649 fix[update-arango-graph] - creates a missing collection in already pr…
  Makefile
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/arangodb/edgeCollections.go
Labels: size/XL

#1630 Utilize gocloud and blob store to work around pubsub message size
  cmd/README.md
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/files.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guaccollect/cmd/root.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  container_files/arango/guac.yaml
  container_files/ent/guac.yaml
  container_files/guac/guac.yaml
  container_files/neo4j/guac.yaml
  container_files/redis/guac.yaml
  container_files/tikv/guac.yaml
  go.mod
  go.sum
  guac.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/cli/store.go
  pkg/events/events.go
  pkg/events/events_test.go
  pkg/handler/collector/collector.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process.go
Labels: size/XL

#1658 fix: s3 collector
  cmd/guacone/cmd/s3.go
  go.mod
  go.sum
  pkg/handler/collector/s3/bucket/bucket.go
  pkg/handler/collector/s3/s3.go
Labels: size/L

#1635 Included prometheus server for guacql
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  go.mod
  go.sum
  pkg/cli/init.go
Labels: size/M

#1661 Add Deps.dev collector to guacone
  cmd/guacone/cmd/deps_dev.go
Labels: size/L

#1664 abstract pubsub service via gocloud
  cmd/README.md
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/files.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guaccollect/cmd/root.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  container_files/arango/guac.yaml
  container_files/ent/guac.yaml
  container_files/guac/guac.yaml
  container_files/nats/js.conf
  container_files/neo4j/guac.yaml
  container_files/redis/guac.yaml
  container_files/tikv/guac.yaml
  go.mod
  go.sum
  guac.yaml
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/cmd/pubsub_test/cmd/root.go
  k8s/k8s.yaml
  pkg/blob/blob.go
  pkg/blob/blob_test.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/cli/store.go
  pkg/emitter/emitter.go
  pkg/emitter/emitter_test.go
  pkg/emitter/nats_data.go
  pkg/emitter/nats_emitter.go
  pkg/emitter/nats_emitter_test.go
  pkg/handler/collector/collector.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/process/process_test.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
Labels: size/XXL

#1666 Update default `blob-addr` to use filesystem (for docker-compose and k8s)
  container_files/arango/guac.yaml
  container_files/ent/guac.yaml
  container_files/guac/guac.yaml
  container_files/neo4j/guac.yaml
  container_files/redis/guac.yaml
  container_files/tikv/guac.yaml
  docker-compose.yml
  guac.yaml
  k8s/k8s.yaml
  pkg/cli/store.go
Labels: size/M

#1566 Github Collector Enhancements
  cmd/guaccollect/cmd/github.go
  internal/client/githubclient/githubclient.go
  internal/client/githubclient/githubclient_test.go
  internal/client/repo_client.go
  pkg/cli/store.go
  pkg/handler/collector/github/github.go
  pkg/handler/collector/github/github_test.go
Labels: size/L

#1647 update dsse processor to not guess unpacked payload
  pkg/handler/processor/dsse/dsse.go
  pkg/handler/processor/dsse/dsse_test.go
Labels: size/M

#1674 Error and exit when initialization fails
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/files.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/s3.go
  internal/testing/cmd/ingest/cmd/example.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
Labels: size/M
