Repository guacsec/guac, pull requests merged in 2024-07, with the labels that each got.

#1988 Update slsa parser to remove deprecated structs
  go.mod
  go.sum
  internal/testing/testdata/exampledata/ingest_predicates.json
  internal/testing/testdata/testdata.go
  pkg/assembler/assembler_test.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/slsa/parser_slsa_test.go
Labels: size/L

#1999 Speed up common CertifyVuln ent queries by adding indexes
  .github/PULL_REQUEST_TEMPLATE.md
  pkg/assembler/backends/ent/migrate/migrations/20240702195630_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifyvuln.go
  pkg/assembler/backends/ent/schema/vulnerabilityid.go
Labels: size/S

#1997 [ENT] #1996 Improve package's qualifiers query
  internal/testing/backend/hasMetadata_test.go
  internal/testing/testdata/models.go
  pkg/assembler/backends/ent/packageversion/qualifier_predicates.go
Labels: size/M

#1989 [ENT] add missing nodes from the node query
  internal/testing/backend/path_test.go
  pkg/assembler/backends/ent/backend/neighbors.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/L

#2000 Fixed Guacone Query Vuln When Keyvalue is Used
  cmd/guacone/cmd/vulnerability.go
Labels: size/XS

#2001 Fix guacrest docker compose healthchecks
  Makefile
  container_files/guac-demo-compose.yaml
  docker-compose.yml
Labels: size/XS

#1998 Include e2e tests for `guaccollect`, `guacingest`, and ent
  .github/workflows/ci.yaml
  internal/testing/e2e/e2e
Labels: size/L, needs-review

#2010 Fix the e2e
  internal/testing/e2e/e2e
Labels: size/XS

#1933 remove GetMatchFlagsFromPkgInput helper as it was not needed for isDependency
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#2017 Fix the shebang on the e2e script
  internal/testing/e2e/e2e
Labels: size/XS, needs-review

#2020 Speed up isDependency query when spec depPkg has pkgID (add ent Pg index)
  pkg/assembler/backends/ent/migrate/migrations/20240712193834_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/dependency.go
Labels: size/XS

#2031 add check for paginated queries for nil values in ent
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hashequal.go
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnMetadata.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/L

#2032 [ENT] add indexes for common queries on ENT
  internal/testing/testdata/exampledata/ingest_predicates.json
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/ent/migrate/migrations/20240716182144_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/billofmaterials.go
  pkg/assembler/backends/ent/schema/certifylegal.go
  pkg/assembler/backends/ent/schema/dependency.go
  pkg/assembler/backends/ent/schema/occurrence.go
Labels: size/M

#2039 update to skip type guac purls in deps.dev
  pkg/handler/collector/deps_dev/deps_dev.go
Labels: size/M

#2046 move timestamp up such that it is not skipped
  pkg/handler/collector/deps_dev/deps_dev.go
Labels: size/XS
