Repository guacsec/guac, pull requests merged in 2024-11, with the labels that each got.

#2252 check if batch query is empty, otherwise skip
  pkg/assembler/backends/ent/backend/search.go
Labels: size/L

#2185 Feat/oci registry collector
  .gitignore
  go.mod
  internal/testing/mockRegistry/mock_registry.go
  internal/testing/mockRegistry/mock_registry_test.go
  pkg/collectsub/datasource/datasource.go
  pkg/handler/collector/collector.go
  pkg/handler/collector/oci/oci.go
  pkg/handler/collector/oci/oci_registry.go
  pkg/handler/collector/oci/oci_registry_test.go
Labels: size/XXL, needs-review

#2254 Add CertifyLegal to query known package
  cmd/guacone/cmd/known.go
Labels: size/M, needs-review

#2266 Fix: jsonl files are rejected
  pkg/handler/processor/guesser/guesser.go
  pkg/handler/processor/jsonlines/jsonlines.go
  pkg/handler/processor/jsonlines/jsonlines_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/processor.go
  pkg/ingestor/parser/opaque/opaque_parser.go
  pkg/ingestor/parser/opaque/opaque_parser_test.go
  pkg/ingestor/parser/parser.go
Labels: size/L

#2216 Updated GraphQL Testing
  internal/testing/graphqlClients/guacdata.go
Labels: size/M, needs-review

#2279 Attempt to fix tilt-ci flakiness
  .github/workflows/ci.yaml
Labels: size/XS

#2291 skip clearly defined tests for now because of flake
  pkg/certifier/clearlydefined/clearlydefined_test.go
Labels: size/XS

#2243 Export getGraphqlServer and accept initialized backend
  cmd/guacgql/cmd/server.go
  pkg/assembler/server/server.go
  pkg/assembler/server/server_test.go
Labels: size/M, needs-review

#2276 Fix zizmor audits
  .github/workflows/db-performance-test.yaml
  .github/workflows/nightly-release.yaml
  .github/workflows/postmerge.yaml
  .github/workflows/release.yaml
  .github/workflows/reusable-local-build.yaml
  .github/zizmor.yml
Labels: size/M

#2268 Don't persist credentials in actions/checkout
  .github/workflows/ci.yaml
Labels: size/S

#2278 Add depsdev guac client as a stepping stone to split up depsdev functionality
  internal/client/depsdevclient/deps_dev_client.go
  internal/client/depsdevclient/deps_dev_client_test.go
Labels: size/XXL

#2297 skip scanner cd test due to service timeout
  pkg/ingestor/parser/common/scanner/scanner_test.go
Labels: size/XS

#2288 Fix/overwrite collector registration
  pkg/handler/collector/collector.go
  pkg/handler/collector/collector_test.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/gcs/gcs_test.go
  pkg/handler/collector/git/git_test.go
  pkg/handler/collector/github/github_test.go
  pkg/handler/collector/oci/oci_registry_test.go
  pkg/handler/collector/oci/oci_test.go
  pkg/handler/collector/s3/s3_test.go
Labels: size/M

#2307 bugfix: fixes service-poll env variable bug in s3
  cmd/guaccollect/cmd/s3.go
Labels: size/XS

#2310 Improve test output formatting
  Makefile
Labels: size/S

#2262 clearly defined url encode/add hyphen for namespace
  pkg/misc/coordinates/coordinates.go
  pkg/misc/coordinates/coordinates_test.go
Labels: size/M

#2247 Decouple backend specific config from guacgql cmd
  cmd/guacgql/cmd/ent.go
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/ent/backend/register.go
  pkg/assembler/backends/keyvalue/backend.go
  pkg/assembler/backends/keyvalue/tikv.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neptune/neptune.go
  pkg/assembler/backends/register.go
  pkg/cli/store.go
Labels: size/XL
