Repository guacsec/guac, pull requests merged in 2024-09, with the labels that each got.

#2101 Fix SPDX SBOM ingestion with multiple purls in externalRefs array
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/L

#2108 Bumping cdevents/sdk-go from 0.3.2 to 0.4.1
  go.mod
  go.sum
  pkg/events/events.go
Labels: size/M

#2111 Include documentRef in hasSBOM client operations
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/trees.graphql
Labels: size/M

#2112 Bump getkin/kin-openapi from `v0.123.0` to `v0.127.0`
  go.mod
  go.sum
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/openapi.go
  tools/tools.go
Labels: size/M

#2114 change atlas migration to take into account ent auto migration index names
  pkg/assembler/backends/ent/migrate/migrations/20240826162616_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
Labels: size/XS

#2115 add connection timeout for ENT
  cmd/guacgql/cmd/ent.go
  cmd/guacgql/cmd/root.go
  pkg/assembler/backends/ent/backend/migrations.go
  pkg/cli/store.go
Labels: size/M

#2122 retry on network error for certifiers
  cmd/guaccollect/cmd/osv.go
  pkg/certifier/certify/certify.go
Labels: size/M

#2125 [Fix] GRPC rate limit and add exponential backoff for CD
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/osv.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  go.mod
  go.sum
  pkg/certifier/certify/certify.go
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/clients/grpcRateLimiter.go
  pkg/clients/grpcRateLimiter_test.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
Labels: size/XL

#2129 Add the ClearlyDefined certifier to the demo compose file
  container_files/guac-demo-compose.yaml
Labels: size/S

#1965 Searching for hasSBOMs via Artifacts in Vuln cli
  cmd/guacone/cmd/vulnerability.go
  pkg/guacanalytics/searchForSBOM.go
Labels: size/XL, needs-review

#2134 Update CD certifier to ignore LicenseRef licenses
  pkg/ingestor/parser/clearlydefined/clearlydefined.go
  pkg/ingestor/parser/common/license.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/S

#2130 Also add the ClearlyDefined certifier to the postgres compose file
  container_files/guac-postgres-compose.yaml
Labels: size/S

#2126 CDX parser captures version as an artifact for images
  internal/testing/testdata/exampledata/distroless-cyclonedx-invalid-version.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#2136 Fix guacEmpty being added into the ENT DB causing errors
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/migrate/migrations/20240918165345.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/helpers/source.go
  pkg/assembler/helpers/source_test.go
Labels: size/L

#2137 [CDX] create isoccur for top level package when artifact is found
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
Labels: size/S

#2139 [ENT] drop discovered_license from required index on certifyLegal
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/migrate/migrations/20240919142722_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifylegal.go
Labels: size/S

#2140 fix bugs that causes panic on query vuln on sbom uri search
  cmd/guacone/cmd/vulnerability.go
Labels: size/S

#2149 add logs to determine when certifier starts and ends
  pkg/certifier/certify/certify.go
Labels: size/S

#2151 fix error handling on certifier
  cmd/guaccollect/cmd/osv.go
  pkg/certifier/certify/certify.go
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/certifier/osv/osv.go
  pkg/ingestor/parser/common/scanner/scanner.go
Labels: size/M

#2152 improve on ingestion license check
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/ingestor/parser/common/scanner/scanner.go
  pkg/ingestor/parser/common/scanner/scanner_test.go
  pkg/ingestor/parser/parser.go
Labels: size/L
