Repository guacsec/guac, pull requests merged in 2024-04, with the labels that each got.

#1805 Run the guacgql HTTP server on only one port
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/root.go
  cmd/guacgql/cmd/root.go
  pkg/cli/init.go
  pkg/cli/store.go
  pkg/metrics/README.md
Labels: size/M

#1807 [fix] OSV unit test update and replaced deprecated `types.Descriptor`
  internal/testing/testdata/testdata.go
  pkg/handler/collector/oci/oci.go
Labels: size/S

#1811 Add guaccollect files option to set origin to blob path
  cmd/guaccollect/cmd/files.go
  cmd/guacone/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  pkg/cli/store.go
  pkg/handler/collector/collector_test.go
  pkg/handler/collector/file/file.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/git/git.go
Labels: size/M

#1814 Fix goreleaser flag deprecation warnings
  .github/workflows/release.yaml
  Makefile
Labels: size/XS, needs-review

#1818 Fix GitHub collector to accept explicit tag in urls
  pkg/handler/collector/github/github.go
  pkg/handler/collector/github/github_test.go
Labels: size/S

#1822 Handle null SPDX relationships without panicking
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#1819 Add missing dev tools to nix shell
  shell.nix
Labels: size/XS

#1829 [ENT] FIx node query not returning via builtIn `Noder` function
  pkg/assembler/backends/ent/backend/neighbors.go
Labels: size/M

#1835 [ENT] fix issue with index on artifact
  internal/testing/backend/artifact_test.go
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/artifact.go
Labels: size/M

#1834 Update graphQL schema to add documentRef field to all verbs
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/graphql/generated/artifact.generated.go
  pkg/assembler/graphql/generated/certifyBad.generated.go
  pkg/assembler/graphql/generated/certifyGood.generated.go
  pkg/assembler/graphql/generated/certifyLegal.generated.go
  pkg/assembler/graphql/generated/certifyScorecard.generated.go
  pkg/assembler/graphql/generated/certifyVEXStatement.generated.go
  pkg/assembler/graphql/generated/certifyVuln.generated.go
  pkg/assembler/graphql/generated/contact.generated.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/hasSLSA.generated.go
  pkg/assembler/graphql/generated/hasSourceAt.generated.go
  pkg/assembler/graphql/generated/hashEqual.generated.go
  pkg/assembler/graphql/generated/isDependency.generated.go
  pkg/assembler/graphql/generated/isOccurrence.generated.go
  pkg/assembler/graphql/generated/metadata.generated.go
  pkg/assembler/graphql/generated/pkgEqual.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/generated/vulnEqual.generated.go
  pkg/assembler/graphql/generated/vulnMetadata.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/certifyBad.graphql
  pkg/assembler/graphql/schema/certifyGood.graphql
  pkg/assembler/graphql/schema/certifyLegal.graphql
  pkg/assembler/graphql/schema/certifyScorecard.graphql
  pkg/assembler/graphql/schema/certifyVEXStatement.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
  pkg/assembler/graphql/schema/contact.graphql
  pkg/assembler/graphql/schema/hasSBOM.graphql
  pkg/assembler/graphql/schema/hasSLSA.graphql
  pkg/assembler/graphql/schema/hasSourceAt.graphql
  pkg/assembler/graphql/schema/hashEqual.graphql
  pkg/assembler/graphql/schema/isDependency.graphql
  pkg/assembler/graphql/schema/isOccurrence.graphql
  pkg/assembler/graphql/schema/metadata.graphql
  pkg/assembler/graphql/schema/pkgEqual.graphql
  pkg/assembler/graphql/schema/vulnEqual.graphql
  pkg/assembler/graphql/schema/vulnMetadata.graphql
Labels: size/L

#1831 add new re-designed overview diagram for GUAC
  README.md
Labels: size/XS

#1836 Fix the Overview Diagram
  README.md
Labels: size/XS

#1830 Include a more descriptive debugger for the collector and processor
  cmd/guaccollect/cmd/files.go
  cmd/guacone/cmd/certify.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/dochelper/dochelper.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/certifier/certify/certify.go
  pkg/certifier/certify/certify_test.go
  pkg/handler/collector/collector.go
  pkg/handler/collector/collector_test.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/gcs/gcs_test.go
  pkg/handler/processor/process/process.go
  pkg/handler/processor/process/process_test.go
  pkg/handler/processor/processor.go
  pkg/ingestor/ingestor.go
  pkg/ingestor/parser/parser.go
  pkg/ingestor/parser/parser_test.go
  pkg/logging/logger.go
Labels: size/L

#1845 Add the ability to specify HTTP headers for CLI commands (to support Auth proxies)
  cmd/guacgql/cmd/server.go
  cmd/guacone/cmd/bad.go
  cmd/guacone/cmd/known.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/patch.go
  cmd/guacone/cmd/scorecard.go
  cmd/guacone/cmd/vulnerability.go
  cmd/guacrest/cmd/root.go
  cmd/guacrest/cmd/server.go
  go.mod
  go.sum
  pkg/cli/headers.go
  pkg/cli/headers_test.go
  pkg/cli/init.go
  pkg/cli/store.go
  pkg/cli/testdata/headers.txt
Labels: size/L

#1851 Remove unused variable
  pkg/certifier/certify/certify.go
Labels: size/XS

#1856 Add GUAC Version to Logs
  pkg/logging/logger.go
Labels: size/XS

#1855 [FIX] implement fixes based on parsing and querying errors for CDX
  cmd/guacone/cmd/vulnerability.go
  internal/testing/testdata/exampledata/cyclonedx-vex-no-analysis.json
  internal/testing/testdata/testdata.go
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L, needs-review

#1847 Populate SourceInformation.DocumentRef in collectors
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/files.go
  cmd/guaccollect/cmd/gcs.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/oci.go
  cmd/guaccollect/cmd/root.go
  cmd/guaccollect/cmd/s3.go
  cmd/guacone/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/dochelper/dochelper.go
  pkg/cli/store.go
  pkg/events/events.go
  pkg/handler/collector/collector_test.go
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/handler/collector/file/file.go
  pkg/handler/collector/file/file_test.go
  pkg/handler/collector/gcs/gcs.go
  pkg/handler/collector/gcs/gcs_test.go
  pkg/handler/collector/git/git.go
  pkg/handler/collector/github/README.md
  pkg/handler/collector/github/github.go
  pkg/handler/collector/github/github_test.go
  pkg/handler/collector/oci/oci.go
  pkg/handler/collector/oci/oci_test.go
  pkg/handler/collector/s3/s3.go
  pkg/handler/collector/s3/s3_test.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/L, needs-review

#1863 [ENT] fix trie output for package, source and vulnerability
  pkg/assembler/backends/ent/backend/helpers.go
  pkg/assembler/backends/ent/backend/neighbors.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/L

#1866 feat: switch `golang/mock` to `uber-go/mock`
  go.mod
  go.sum
  internal/testing/mocks/backend.go
  internal/testing/mocks/documentparser.go
  internal/testing/mocks/mockgen.go
  internal/testing/mocks/scorecard.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyGood.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyLegal.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyScorecard.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyVEXStatement.resolvers_test.go
  pkg/assembler/graphql/resolvers/certifyVuln.resolvers_test.go
  pkg/assembler/graphql/resolvers/contact.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSBOM.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSLSA.resolvers_test.go
  pkg/assembler/graphql/resolvers/hasSourceAt.resolvers_test.go
  pkg/assembler/graphql/resolvers/hashEqual.resolvers_test.go
  pkg/assembler/graphql/resolvers/isDependency.resolvers_test.go
  pkg/assembler/graphql/resolvers/isOccurrence.resolvers_test.go
  pkg/assembler/graphql/resolvers/license.resolvers_test.go
  pkg/assembler/graphql/resolvers/metadata.resolvers_test.go
  pkg/assembler/graphql/resolvers/package.resolver_test.go
  pkg/assembler/graphql/resolvers/path.resolvers_test.go
  pkg/assembler/graphql/resolvers/pkgEqual.resolvers_test.go
  pkg/assembler/graphql/resolvers/source.resolvers_test.go
  pkg/assembler/graphql/resolvers/vulnEqual.resolvers_test.go
  pkg/assembler/graphql/resolvers/vulnMetadata.resolvers_test.go
  pkg/assembler/graphql/resolvers/vulnerability.resolvers_test.go
  pkg/certifier/scorecard/scorecard_test.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/parser_test.go
  tools/tools.go
Labels: size/M

#1869 Go generate
  internal/testing/mocks/backend.go
Labels: size/XS

#1867 Add a transitive dependencies endpoint to the REST API
  cmd/guacrest/cmd/server.go
  internal/testing/graphqlClients/guacdata.go
  internal/testing/graphqlClients/testsetup.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hashEqual.graphql
  pkg/assembler/clients/operations/isOccurrence.graphql
  pkg/assembler/helpers/purl.go
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/helpers/artifact.go
  pkg/guacrest/helpers/artifact_test.go
  pkg/guacrest/helpers/errors.go
  pkg/guacrest/helpers/package.go
  pkg/guacrest/helpers/package_test.go
  pkg/guacrest/openapi.yaml
  pkg/guacrest/pagination/pagination.go
  pkg/guacrest/pagination/pagination_test.go
  pkg/guacrest/server/errors.go
  pkg/guacrest/server/retrieveDependencies.go
  pkg/guacrest/server/retrieveDependencies_test.go
  pkg/guacrest/server/server.go
  pkg/logging/logger.go
Labels: size/XXL

#1868 Add standalone postgres compose
  .github/workflows/release.yaml
  container_files/guac-postgres-compose.yaml
Labels: size/L

#1870 [ENT] Complete ent pagination and update backend tests
  internal/testing/backend/artifact_test.go
  internal/testing/backend/builder_test.go
  internal/testing/backend/certifyBad_test.go
  internal/testing/backend/certifyGood_test.go
  internal/testing/backend/certifyLegal_test.go
  internal/testing/backend/certifyScorecard_test.go
  internal/testing/backend/certifyVEXStatement_test.go
  internal/testing/backend/certifyVuln_test.go
  internal/testing/backend/hasMetadata_test.go
  internal/testing/backend/hasSBOM_test.go
  internal/testing/backend/hasSLSA_test.go
  internal/testing/backend/hasSourceAt_test.go
  internal/testing/backend/hashEqual_test.go
  internal/testing/backend/isDependency_test.go
  internal/testing/backend/isOccurrence_test.go
  internal/testing/backend/license_test.go
  internal/testing/backend/main_test.go
  internal/testing/backend/pkgEqual_test.go
  internal/testing/backend/pkg_test.go
  internal/testing/backend/pointOfContact_test.go
  internal/testing/backend/src_test.go
  internal/testing/backend/vulnEqual_test.go
  internal/testing/backend/vulnMetadata_test.go
  internal/testing/backend/vulnerability_test.go
  pkg/assembler/backends/arangodb/certifyGood.go
  pkg/assembler/backends/arangodb/certifyLegal.go
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hashequal.go
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/transforms.go
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnMetadata.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/XXL

#1852 Fixes to HTTP Header functionality for CLI commands
  cmd/guaccollect/cmd/gcs.go
  cmd/guaccollect/cmd/s3.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/bad.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/gcs_test.go
  cmd/guacone/cmd/github.go
  cmd/guacone/cmd/known.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/patch.go
  cmd/guacone/cmd/root.go
  cmd/guacone/cmd/s3.go
  cmd/guacone/cmd/scorecard.go
  cmd/guacone/cmd/vulnerability.go
  cmd/guacrest/cmd/server.go
  pkg/cli/headers.go
  pkg/cli/headers_test.go
  pkg/ingestor/ingestor.go
  pkg/logging/logger.go
Labels: size/L

#1873 Update readme with supported backends.
  README.md
Labels: size/M

#1874 [FIX] Ingestor should not ack message on failure
  cmd/guacingest/cmd/ingest.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/handler/processor/process/process.go
Labels: size/M
