Repository guacsec/guac, pull requests merged in 2024-03, with the labels that each got.

#1738 Fix License node ingestion when no LicenseListVersion provided.
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/XS

#1748 ENT - update hasSBOM ingestion for large SBOMs and increase batch size
  pkg/assembler/backends/ent/backend/artifact.go
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/ent/backend/builders.go
  pkg/assembler/backends/ent/backend/certify.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/hashequal.go
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/backend/occurrence.go
  pkg/assembler/backends/ent/backend/package.go
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/pointOfContact.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnMetadata.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/L

#1747 Add a demo level docker compose yaml
  .github/workflows/release.yaml
  container_files/guac-demo-compose.yaml
Labels: size/M

#1751 Fixed typos
  cmd/guaccollect/cmd/files.go
  cmd/guacingest/cmd/ingest.go
  internal/testing/cmd/pubsub_test/cmd/files.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  pkg/blob/blob_test.go
  pkg/certifier/certify/certify_test.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process_test.go
Labels: size/S

#1678 Included Polling for Github Collect
  pkg/handler/collector/github/github.go
Labels: size/S

#1753 move message acknowledgment for pubsub to be done after the ingestion has occured
  pkg/certifier/certify/certify_test.go
  pkg/emitter/emitter.go
  pkg/emitter/nats_emitter_test.go
  pkg/handler/collector/collector_test.go
  pkg/handler/processor/process/process.go
Labels: size/M

#1731 README for the Github Collector
  pkg/handler/collector/github/READMD.md
Labels: size/M

#1750 adds helper function to check for an arango collection index
  pkg/assembler/backends/arangodb/backend.go
Labels: size/XL

#1752 Fixed flaky test
  internal/client/githubclient/githubclient_test.go
Labels: size/S

#1720 Add Pagination to the Rest API
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/openapi.yaml
  pkg/guacrest/pagination/cursor.go
  pkg/guacrest/pagination/pagination.go
  pkg/guacrest/pagination/pagination_test.go
  pkg/guacrest/server/server.go
Labels: size/L

#1757 Remove empty depends_on that fails validation.
  container_files/guac-demo-compose.yaml
Labels: size/XS

#1779 Support image references by digest in the OCI collector
  pkg/handler/collector/oci/oci.go
  pkg/handler/collector/oci/oci_test.go
Labels: size/L

#1791 Included Query for Scorecard
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyScorecard.graphql
Labels: size/XS

#1790 [ENT] Fix all broken queries from the backend test suite
  internal/testing/backend/hasSBOM_test.go
  internal/testing/backend/isOccurrence_test.go
  internal/testing/backend/main_test.go
  internal/testing/backend/pkgEqual_test.go
  internal/testing/backend/search_test.go
  internal/testing/backend/vulnEqual_test.go
  internal/testing/backend/vulnerability_test.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/dependency.go
  pkg/assembler/backends/ent/backend/hasMetadata.go
  pkg/assembler/backends/ent/backend/pkgequal.go
  pkg/assembler/backends/ent/backend/scorecard.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/backends/ent/backend/source.go
  pkg/assembler/backends/ent/backend/vulnEqual.go
  pkg/assembler/backends/ent/backend/vulnMetadata.go
  pkg/assembler/backends/ent/backend/vulnerability.go
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/hasmetadata.go
  pkg/assembler/backends/ent/schema/hassourceat.go
  pkg/assembler/backends/ent/schema/slsaattestation.go
  pkg/assembler/backends/ent/slsaattestation.go
  pkg/assembler/backends/ent/slsaattestation/where.go
  pkg/assembler/backends/ent/slsaattestation_create.go
  pkg/assembler/backends/ent/slsaattestation_update.go
  pkg/assembler/backends/keyvalue/search.go
Labels: size/L

#1719 Included a README for guacrest
  cmd/guacrest/README.md
Labels: size/M

#1792 add guacrest to docker and go releaser
  container_files/guac-demo-compose.yaml
  docker-compose.yml
  dockerfiles/Dockerfile.goreleaser
  guac.yaml
Labels: size/M

#1793 fix health check for rest api
  container_files/guac-demo-compose.yaml
  container_files/guac/guac.yaml
Labels: size/XS
