Repository guacsec/guac, pull requests merged in 2024-05, with the labels that each got.

#1887 [ENT] Versioned Migration via Atlas
  .github/workflows/ci.yaml
  Makefile
  pkg/assembler/backends/ent/migrate/migrations/20240503123155_baseline.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/billofmaterials.go
  pkg/assembler/backends/ent/schema/certifyvex.go
  pkg/assembler/backends/ent/schema/dependency.go
  pkg/assembler/backends/ent/schema/hasmetadata.go
  pkg/assembler/backends/ent/schema/occurrence.go
  pkg/assembler/backends/ent/schema/pointofcontact.go
Labels: size/L

#1871 Update S3 collector to support collecting from a directory within the bucket
  cmd/guaccollect/cmd/s3.go
  cmd/guacone/cmd/s3.go
  pkg/cli/store.go
  pkg/handler/collector/s3/bucket/bucket.go
  pkg/handler/collector/s3/s3.go
  pkg/handler/collector/s3/s3_test.go
Labels: size/M

#1902 add issues/1885 reviewer/owners
  CONTRIBUTING.md
Labels: size/S

#1891 add missing atlas to post merge CI
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
Labels: size/XS

#1883 Attach hasSBOM nodes to artifacts instead of packages
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/spdx/parse_spdx.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
  pkg/logging/logger.go
Labels: size/XL, needs-review

#1905 Include Aggregated Json Logs
  pkg/handler/processor/process/process.go
Labels: size/S, needs-review

#1915 [ENT] add bulk ingest for hasSBOM nodes
  pkg/assembler/backends/ent/backend/sbom.go
Labels: size/L

#1904 Include Pagination for KeyValue
  internal/testing/backend/helpers_test.go
  internal/testing/backend/main_test.go
  pkg/assembler/backends/keyvalue/artifact.go
  pkg/assembler/backends/keyvalue/builder.go
  pkg/assembler/backends/keyvalue/certifyBad.go
  pkg/assembler/backends/keyvalue/certifyGood.go
  pkg/assembler/backends/keyvalue/certifyLegal.go
  pkg/assembler/backends/keyvalue/certifyScorecard.go
  pkg/assembler/backends/keyvalue/certifyVEXStatement.go
  pkg/assembler/backends/keyvalue/certifyVuln.go
  pkg/assembler/backends/keyvalue/hasMetadata.go
  pkg/assembler/backends/keyvalue/hasSBOM.go
  pkg/assembler/backends/keyvalue/hasSLSA.go
  pkg/assembler/backends/keyvalue/hasSourceAt.go
  pkg/assembler/backends/keyvalue/hashEqual.go
  pkg/assembler/backends/keyvalue/isDependency.go
  pkg/assembler/backends/keyvalue/isOccurrence.go
  pkg/assembler/backends/keyvalue/license.go
  pkg/assembler/backends/keyvalue/pkg.go
  pkg/assembler/backends/keyvalue/pkgEqual.go
  pkg/assembler/backends/keyvalue/pointOfContact.go
  pkg/assembler/backends/keyvalue/src.go
  pkg/assembler/backends/keyvalue/vulnEqual.go
  pkg/assembler/backends/keyvalue/vulnMetadata.go
  pkg/assembler/backends/keyvalue/vulnerability.go
  pkg/assembler/graphql/examples/artifact_builder.gql
  pkg/assembler/graphql/examples/certify_bad.gql
  pkg/assembler/graphql/examples/certify_good.gql
  pkg/assembler/graphql/examples/certify_legal.gql
  pkg/assembler/graphql/examples/certify_scorecard.gql
  pkg/assembler/graphql/examples/certify_vex.gql
  pkg/assembler/graphql/examples/certify_vuln.gql
  pkg/assembler/graphql/examples/has_metadata.gql
  pkg/assembler/graphql/examples/has_sbom.gql
  pkg/assembler/graphql/examples/has_slsa.gql
  pkg/assembler/graphql/examples/has_source_at.gql
  pkg/assembler/graphql/examples/hash_equal.gql
  pkg/assembler/graphql/examples/is_dependency.gql
  pkg/assembler/graphql/examples/is_occurence.gql
  pkg/assembler/graphql/examples/license.gql
  pkg/assembler/graphql/examples/packages.gql
  pkg/assembler/graphql/examples/pkg_equal.gql
  pkg/assembler/graphql/examples/point_of_contact.gql
  pkg/assembler/graphql/examples/source.gql
  pkg/assembler/graphql/examples/vulnEqual.gql
  pkg/assembler/graphql/examples/vuln_metadata.gql
  pkg/assembler/graphql/examples/vulnerability.gql
Labels: size/XXL, needs-review

#1916 expose hasSBOM pagination query on client side
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSBOM.graphql
Labels: size/S

#1925 expose vulnerability pagination query on client side
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/hasSBOM.graphql
  pkg/assembler/clients/operations/vulnerability.graphql
Labels: size/S

#1705 Get Next Actionable Critical Dependencies Part 1
  cmd/guacone/cmd/vulnerability.go
  pkg/dependencies/dependents.go
  pkg/dependencies/dependents_test.go
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/openapi.yaml
  pkg/guacrest/server/server.go
Labels: size/XL

#1924 fix: close file
  pkg/collectsub/datasource/filesource/filesource.go
Labels: size/XS

#1733 Add a release process documentation to GUAC
  RELEASES.md
Labels: size/M

#1903 Improved cdx parsing
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M, needs-review

#1936 expose certifyVuln and hasSLSA query and pagination query on client side
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/certifyVuln.graphql
  pkg/assembler/clients/operations/hasSLSA.graphql
  pkg/assembler/clients/operations/trees.graphql
Labels: size/XXL

#1937 use underscore instead of colon for blob store key
  pkg/events/events.go
  pkg/events/events_test.go
Labels: size/M

#1872 update certifier to use paginated query for package and source
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/operations/package.graphql
  pkg/assembler/clients/operations/source.graphql
  pkg/assembler/clients/operations/trees.graphql
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
Labels: size/L

#1939 [FIX] novuln check for ent query
  cmd/guacingest/cmd/ingest.go
  pkg/assembler/backends/ent/backend/vulnerability.go
Labels: size/S
