Repository guacsec/guac, pull requests merged in 2024-02, with the labels that each got.

#1681 add purl helper to convert from allPkgTree fragment
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
Labels: size/L

#1682 removing MAX_CONCURRENT_JOBS
  cmd/guacone/cmd/files.go
Labels: size/S

#1695 Improve guac query vuln error message
  cmd/guacone/cmd/vulnerability.go
  cmd/guacrest/vulnerability.go
Labels: size/S

#1546 Use filename as qualifier for SBOM file references
  internal/testing/testdata/exampledata/ingest_predicates.json
  pkg/assembler/helpers/purl.go
  pkg/assembler/helpers/purl_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
Labels: size/M

#1665 [Rest API] Adds the initial API Spec and guacrest cli.
  .github/PULL_REQUEST_TEMPLATE.md
  cmd/guacrest/README.md
  cmd/guacrest/bad.go
  cmd/guacrest/bad_test.go
  cmd/guacrest/cmd/root.go
  cmd/guacrest/cmd/server.go
  cmd/guacrest/design.md
  cmd/guacrest/docs/docs.go
  cmd/guacrest/docs/swagger.json
  cmd/guacrest/docs/swagger.yaml
  cmd/guacrest/known.go
  cmd/guacrest/known_test.go
  cmd/guacrest/main.go
  cmd/guacrest/vulnerability.go
  cmd/guacrest/vulnerability_test.go
  go.mod
  go.sum
  pkg/cli/store.go
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/openapi.go
  pkg/guacrest/openapi.yaml
  pkg/guacrest/server/server.go
  tools/tools.go
Labels: size/XXL

#1707 Bump entgo.io/ent v0.13.0
  go.mod
  go.sum
  pkg/assembler/backends/ent/runtime/runtime.go
Labels: size/S

#1718 separate software IDs into packages and artifacts for hasSBOM ingestion
  internal/testing/backend/hasSBOM_test.go
  internal/testing/backend/path_test.go
  pkg/assembler/backends/arangodb/hasSBOM.go
  pkg/assembler/backends/ent/backend/sbom.go
  pkg/assembler/backends/keyvalue/hasSBOM.go
  pkg/assembler/clients/generated/operations.go
  pkg/assembler/clients/helpers/assembler.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/assembler/graphql/generated/hasSBOM.generated.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/model/nodes.go
  pkg/assembler/graphql/schema/hasSBOM.graphql
Labels: size/L

#1675 Included http middleware to measure the graphql response times using prometheus.
  cmd/guacgql/cmd/server.go
  pkg/cli/init.go
  pkg/metrics/metrics.go
  pkg/metrics/prometheus.go
Labels: size/L, needs-review

#1723 Update CONTRIBUTING.md about DCO and CLA.
  CONTRIBUTING.md
Labels: size/S

#1711 Implemented key value search
  internal/testing/backend/main_test.go
  internal/testing/backend/search_test.go
  pkg/assembler/backends/keyvalue/search.go
Labels: size/L

#1730 Fix the incorrect `callingFuncName` in the `getNeighborIDFromCursor` function within the arangodb/certifyVEXStatement.go file
  pkg/assembler/backends/arangodb/certifyVEXStatement.go
Labels: size/XS

#1735 attempt to fix golangci-lint issues
  .github/workflows/ci.yaml
Labels: size/XS
