Repository guacsec/guac, pull requests merged in 2024-12, with the labels that each got.

#2338 Adjust workflow permissions for signing and publishing
  .github/workflows/release.yaml
Labels: size/S

#2339 fix: handles the case where empty pkgIDs slice is passed
  pkg/assembler/backends/keyvalue/search.go
Labels: size/XS

#2341 Really fix the permissions this time
  .github/workflows/release.yaml
Labels: size/XS

#2326 Reduce scorecard workflow permissions scope
  .github/workflows/scorecard.yml
Labels: size/XS

#2344 Give SLSA generator necessary permission
  .github/workflows/release.yaml
Labels: size/S

#2347 add package write to slsa workflow for release
  .github/workflows/release.yaml
Labels: size/XS

#2356 Fix flag defaults not registered in guacrest binary
  cmd/guacrest/cmd/root.go
Labels: size/S

#2357 add contents write permission for goreleaser workflow
  .github/workflows/release.yaml
Labels: size/XS

#2360 Grant write permissions to the sbom generation
  .github/workflows/release.yaml
Labels: size/XS

#2365 Add check for empty CertifyBad nodes in query bad
  cmd/guacone/cmd/bad.go
Labels: size/XS

#2370 [FIX] Update batch query vulns to return all values, including novulns
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/S

#2371 [FIX] CDX vulnerability parsing and update ENT VEX index
  internal/testing/backend/certifyVEXStatement_test.go
  internal/testing/testdata/exampledata/xray-cdx-vulns.json
  internal/testing/testdata/testdata.go
  pkg/assembler/backends/ent/backend/certifyVEXStatement.go
  pkg/assembler/backends/ent/migrate/migrations/20241216154012_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifyvex.go
  pkg/assembler/graphql/resolvers/certifyBad.resolvers_test.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#2383 update depsdev collector to use depsdevclient
  pkg/handler/collector/deps_dev/deps_dev.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/handler/processor/deps_dev/deps_dev.go
  pkg/handler/processor/guesser/type_deps_dev.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
Labels: size/XL

#2388 fix issue where guac.yaml was not being read for backend configuration
  pkg/assembler/backends/arangodb/backend.go
  pkg/assembler/backends/ent/backend/backend.go
  pkg/assembler/backends/keyvalue/backend.go
  pkg/assembler/backends/neo4j/backend.go
  pkg/assembler/backends/neptune/neptune.go
  pkg/assembler/backends/register.go
Labels: size/M

#2385 add depsdev scanner implementation
  pkg/ingestor/parser/common/scanner/scanner.go
  pkg/ingestor/parser/common/scanner/scanner_test.go
Labels: size/L
