Repository guacsec/guac, pull requests merged in 2024-08, with the labels that each got.

#2056 Clarify GUAC's place in the OpenSSF
  README.md
Labels: size/XS

#2009 Fixed incorrect depsdev getProject
  internal/testing/testdata/testdata.go
  pkg/assembler/helpers/vcs.go
  pkg/assembler/helpers/vcs_test.go
  pkg/handler/collector/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/deps_dev/deps_dev_test.go
  pkg/ingestor/parser/spdx/parse_spdx_test.go
  pkg/logging/logger.go
Labels: size/L

#2062 ensure cdx parser does not error on v1.5 or below license parsing
  internal/testing/testdata/exampledata/cdx-v1.4.json
  internal/testing/testdata/testdata.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go
Labels: size/L

#2069 Return hasSBOM and hasSLSA IDs from the assembler
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/annotate_metadata.go
  cmd/guacone/cmd/certify.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/gcs.go
  cmd/guacone/cmd/github.go
  cmd/guacone/cmd/oci.go
  cmd/guacone/cmd/s3.go
  cmd/guacone/cmd/scorecard.go
  pkg/assembler/backends/ent/backend/slsa.go
  pkg/assembler/clients/helpers/bulk.go
  pkg/ingestor/ingestor.go
Labels: size/L

#2060 update dependency schema to make dependent_package_version_id required
  pkg/assembler/backends/ent/dependency/where.go
  pkg/assembler/backends/ent/dependency_create.go
  pkg/assembler/backends/ent/dependency_update.go
  pkg/assembler/backends/ent/gql_edge.go
  pkg/assembler/backends/ent/migrate/migrations/20240802204508_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/dependency.go
Labels: size/XS

#2076 expose hasSBOM and hasSLSA IDs
  pkg/assembler/clients/helpers/bulk.go
Labels: size/S

#2079 [fix] cdx parser empty purl identifier and deduplication
  pkg/ingestor/parser/common/helpers.go
  pkg/ingestor/parser/csaf/parser_csaf.go
  pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go
  pkg/ingestor/parser/deps_dev/deps_dev.go
  pkg/ingestor/parser/open_vex/parser_open_vex.go
  pkg/ingestor/parser/scorecard/parser_scorecard.go
  pkg/ingestor/parser/slsa/parser_slsa.go
  pkg/ingestor/parser/spdx/parse_spdx.go
Labels: size/M

#2080 remove daysSinceLastScan as it is redundant with certifier interval
  cmd/guaccollect/cmd/license.go
  cmd/guaccollect/cmd/osv.go
  cmd/guaccollect/cmd/scorecard.go
  cmd/guacone/cmd/license.go
  cmd/guacone/cmd/osv.go
  cmd/guacone/cmd/scorecard.go
  container_files/guac/guac.yaml
  guac.yaml
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/e2e/e2e
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/components/source/source.go
  pkg/certifier/components/source/source_test.go
  pkg/cli/store.go
Labels: size/XL

#2086 Atlas migration image
  .github/workflows/release.yaml
  pkg/assembler/backends/ent/migrate/Dockerfile
  pkg/assembler/backends/ent/migrate/README.md
  pkg/assembler/backends/ent/migrate/atlas.sh
Labels: size/M

#2087 atlas migration update to build/publish only on tag release
  .github/workflows/release.yaml
  pkg/assembler/backends/ent/migrate/atlas.sh
Labels: size/XS

#2088 Add batch querying for clearly defined to reduce ingestion time
  cmd/guaccollect/cmd/license.go
  cmd/guaccollect/cmd/osv.go
  cmd/guacone/cmd/license.go
  cmd/guacone/cmd/osv.go
  internal/testing/cmd/pubsub_test/cmd/osv.go
  internal/testing/dochelper/dochelper.go
  internal/testing/testdata/exampledata/cd-common-text.json
  internal/testing/testdata/exampledata/cd-log4j.json
  internal/testing/testdata/exampledata/cd-source-common-text.json
  internal/testing/testdata/exampledata/cd-source-log4j.json
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/migrate/migrations/20240826162616_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifylegal.go
  pkg/certifier/attestation/attestation_license.go
  pkg/certifier/certify/certify_test.go
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/certifier/clearlydefined/clearlydefined_test.go
  pkg/certifier/components/root_package/root_package.go
  pkg/certifier/components/root_package/root_package_test.go
  pkg/certifier/osv/osv.go
  pkg/certifier/osv/osv_test.go
  pkg/handler/processor/process/process.go
  pkg/ingestor/parser/clearlydefined/clearlydefined_test.go
  pkg/ingestor/parser/common/scanner/scanner.go
  pkg/ingestor/parser/parser.go
  pkg/misc/coordinates/coordinates.go
Labels: size/XXL
