Repository guacsec/guac, pull requests merged in 2025-03, with the labels that each got.

#2564 fix golang coordinate to ensure valid coordinate
  go.mod
  pkg/misc/coordinates/coordinates.go
  pkg/misc/coordinates/coordinates_test.go
Labels: size/M

#2562 update ent to fix release workflow
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
  .goreleaser-nightly.yaml
  .goreleaser.yaml
  go.mod
  go.sum
  pkg/assembler/backends/ent/runtime/runtime.go
Labels: size/M

#2565 Kubescape collector
  cmd/guaccollect/cmd/kubescape.go
  cmd/guacone/cmd/kubescape.go
  go.mod
  go.sum
  pkg/cli/store.go
  pkg/handler/collector/kubescape/README.md
  pkg/handler/collector/kubescape/kubescape.go
  pkg/handler/collector/kubescape/kubescape_test.go
Labels: size/XL

#2217 Included REST Spec Changes
  pkg/guacrest/client/client.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/server.go
  pkg/guacrest/generated/spec.go
  pkg/guacrest/openapi.yaml
  pkg/guacrest/server/errors.go
  pkg/guacrest/server/retrieveDependencies.go
  pkg/guacrest/server/retrieveDependencies_test.go
  pkg/guacrest/server/server.go
Labels: size/XXL, needs-review

#2568 re-gen code and add retry for other error codes for CD
  pkg/certifier/clearlydefined/clearlydefined.go
  pkg/guacrest/client/models.go
  pkg/guacrest/generated/models.go
  pkg/guacrest/generated/spec.go
Labels: size/XS

#2396 Add eol to e2e and fix certifier logic
  demo/graphql/queries.gql
  internal/testing/e2e/e2e
  internal/testing/e2e/expectEndOfLifeQ1.json
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/keyvalue/search.go
  pkg/certifier/eol/eol.go
  pkg/ingestor/parser/common/scanner/scanner_test.go
  pkg/ingestor/parser/eol/eol.go
Labels: size/L, needs-review
