Repository guacsec/guac, pull requests merged in 2025-01, with the labels that each got.

#2394 Add EOL processor so the certifier will run
  pkg/handler/processor/ite6/ite6.go
  pkg/handler/processor/process/process.go
Labels: size/XS

#2424 Add missing use-csub flag to oci collector
  cmd/guacone/cmd/oci.go
Labels: size/S

#2391 add missing add-eol-on-ingest flag to guacone
  cmd/guacone/cmd/root.go
Labels: size/XS, needs-review

#2440 Add otel instrumentation to http/grpc/sql libraries.
  cmd/guaccollect/cmd/deps_dev.go
  cmd/guaccollect/cmd/github.go
  cmd/guaccollect/cmd/license.go
  cmd/guaccollect/cmd/osv.go
  cmd/guaccollect/cmd/root.go
  cmd/guacgql/cmd/root.go
  cmd/guacgql/cmd/server.go
  cmd/guacingest/cmd/ingest.go
  cmd/guacingest/cmd/root.go
  cmd/guacone/cmd/certifier.go
  cmd/guacone/cmd/deps_dev.go
  cmd/guacone/cmd/eol.go
  cmd/guacone/cmd/files.go
  cmd/guacone/cmd/github.go
  cmd/guacone/cmd/license.go
  cmd/guacone/cmd/osv.go
  go.mod
  go.sum
  internal/client/depsdevclient/deps_dev_client.go
  pkg/assembler/backends/ent/backend/migrations.go
  pkg/certifier/eol/eol.go
  pkg/cli/store.go
  pkg/metrics/README.md
  pkg/metrics/otel.go
  pkg/version/version.go
Labels: size/XL

#2447 Note external updates necessary after a release
  RELEASES.md
Labels: size/XS

#2389 Add "add-depsdev-on-ingest" flag info to cli store
  cmd/guacingest/cmd/ingest.go
  cmd/guacone/cmd/root.go
  pkg/cli/store.go
Labels: size/XS, needs-review

#2453 [ENT] Update license table to use hash of license text
  pkg/assembler/backends/ent/backend/license.go
  pkg/assembler/backends/ent/gql_collection.go
  pkg/assembler/backends/ent/license.go
  pkg/assembler/backends/ent/license/license.go
  pkg/assembler/backends/ent/license/where.go
  pkg/assembler/backends/ent/license_create.go
  pkg/assembler/backends/ent/license_update.go
  pkg/assembler/backends/ent/migrate/migrations/20250124141435_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/mutation.go
  pkg/assembler/backends/ent/schema/license.go
Labels: size/M

#2452 Rework `CertifyVuln` and `CertifyLegal` to upsert and not create duplicate entires
  internal/testing/backend/certifyLegal_test.go
  internal/testing/backend/certifyVuln_test.go
  pkg/assembler/backends/ent/backend/certifyLegal.go
  pkg/assembler/backends/ent/backend/certifyVuln.go
  pkg/assembler/backends/ent/backend/search.go
  pkg/assembler/backends/ent/migrate/migrations/20250122170741_ent_diff.sql
  pkg/assembler/backends/ent/migrate/migrations/atlas.sum
  pkg/assembler/backends/ent/migrate/schema.go
  pkg/assembler/backends/ent/schema/certifylegal.go
  pkg/assembler/backends/ent/schema/certifyvuln.go
  pkg/assembler/backends/keyvalue/certifyLegal.go
  pkg/assembler/backends/keyvalue/certifyVuln.go
  pkg/assembler/graphql/generated/root_.generated.go
  pkg/assembler/graphql/schema/certifyLegal.graphql
  pkg/assembler/graphql/schema/certifyVuln.graphql
Labels: size/L

#2455 Update only depdevclient deps to fix otelgrpc conflicts
  go.mod
  go.sum
Labels: size/L
