Repository guacsec/guac, pull requests merged in 2025-06, with the labels that each got.

#2667 Use separate caches for separate jobs.
  .github/workflows/ci-integration.yaml
  .github/workflows/ci.yaml
  .github/workflows/nightly-release.yaml
  .github/workflows/postmerge.yaml
  .github/workflows/reusable-local-build.yaml
Labels: size/M

#2684 update nats docker image for tests
  .github/workflows/ci-integration.yaml
  docker-compose.yml
Labels: size/XS

#2686 Sync `go-version` in GHA to the one in `go.mod`
  .github/workflows/ci-integration.yaml
  .github/workflows/ci.yaml
  .github/workflows/postmerge.yaml
  .github/workflows/release.yaml
Labels: size/S

#2688 Update GoReleaser configurations
  .goreleaser-nightly.yaml
  .goreleaser.yaml
Labels: size/S
